/**
 * Landing content for Mero Docs.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { Eye, FileText, Folder, Shield, Table } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Docs",
  packageId: "com.calimero.mero-drive-docs",
  tagline: "A document workspace organized by folders, built as a multi-service bundle.",
  dir: "mero-docs",
  markSrc: "/icons/icon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Folders have their own members", "Rich-text editing", "Private by default"],
  explainer: [
    "A document workspace — folders, rich-text documents, and the tags you need to find them again six months later. Each folder holds its own documents separately, so sharing one project does not hand over the whole workspace.",
    "That structure is the point. A folder’s documents replicate only to the people who have that folder, so sharing one project does not hand over the whole workspace.",
  ],
  features: [
    {
      icon: Folder,
      title: "Folders have their own members",
      body: "Each folder’s documents live separately, so access is per folder rather than all-or-nothing.",
    },
    {
      icon: FileText,
      title: "Rich-text documents",
      body: "A real editor with formatting, headings and lists, syncing as you type.",
    },
    {
      icon: Table,
      title: "Tags and archive",
      body: "Organise by tag and retire what is finished without deleting anything.",
    },
    {
      icon: Shield,
      title: "You control the workspace",
      body: "You decide who is a member. Membership is how access works.",
    },
    {
      icon: Eye,
      title: "Per-folder visibility",
      body: "Decide what is shared and what stays yours, folder by folder.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "Mero Docs is built folder by folder, and that structure is the product. Your workspace holds the folder tree, and each folder holds its own documents separately.",
        "That is what makes selective sharing real: giving somebody a folder replicates that folder’s documents to them and nothing else, because the other folders are separate and they were never added to them.",
      ],
      concepts: [
        { term: "Workspace", def: "The workspace you and your members share. It holds the folder tree." },
        { term: "Folder", def: "A folder in the tree, bound once to its own sharing scope. The binding never changes after it is made." },
        { term: "Sharing scope", def: "One folder’s documents. Sharing a folder means adding someone to this scope." },
        { term: "Document", def: "A rich-text document with an id like `doc-3`, allocated by a counter that produces distinct ids even when two people create a document at the same moment." },
        { term: "Owner / manager / folder role", def: "The workspace has one owner and any number of managers who may set roles on any folder. Individual folders can also carry their own per-person roles." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node and pick your node." },
        { title: "Create a workspace", body: "The first person to claim it is the workspace owner." },
        { title: "Make a folder", body: "Creating a folder sets up its own sharing scope right away." },
        { title: "Write", body: "Documents live inside their folder. Editing is collaborative and merges as you type." },
      ],
    },
    {
      id: "sharing",
      heading: "Sharing a folder, not the workspace",
      paragraphs: [
        "Share at folder level. Someone given one folder gets that folder’s documents replicated to their node and has no copy of anything else in the workspace.",
        "Managers may set roles on any folder; a folder role applies to that folder alone. Because each folder keeps its own membership, a revoked member stops receiving its documents rather than merely losing a menu item.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Workspace: folder records, display order, colours and aliases, the owner and managers, and per-folder roles.",
        "Each folder: its documents with their tags and archive state, plus comments, each owned by its author.",
        "Document edits are appended as updates, so concurrent typing merges rather than replacing.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "A shared folder is empty for them", def: "Being in the workspace is not being in the folder. They must be added to that folder itself before its documents replicate." },
        { term: "A folder shows no documents after a move", def: "Moving a folder changes its place in the tree, not what it holds, which is fixed once set. Reload the tree." },
        { term: "Two documents with the same name", def: "Ids are allocated by counter and are always distinct; names are not unique by design. Rename one." },
      ],
    },
  ],
  previewSteps: [
    { title: "A folder’s documents", body: "What you see belongs to one folder. Other folders in the workspace hold their own documents entirely." },
    { title: "An edit merges", body: "Edits append as updates, so two people typing in one document converge instead of overwriting." },
    { title: "A file uploads", body: "Blobs replicate to the members of that folder — and to nobody else in the workspace." },
    { title: "Private by default", body: "A folder is shared with the people you add to it. Nothing is workspace-wide unless you make it so." },
  ],
  loginPopup: LoginPopup,
};
