/**
 * Landing content for Mero Kombat.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { CloudX, ExternalLink, LockCheck, Target, Zap } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Kombat",
  packageId: "com.calimero.mero-kombat",
  tagline: "A one-on-one arcade fighting game with no game server. An arena is a Calimero context: every punch, kick and special is a transaction executed by the contract on both fighters' own nodes, and health, rounds and the winner are derived from them.",
  dir: "mero-kombat",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  playableOffline: true,
  trust: ["No game server", "Every blow is a transaction", "No accounts"],
  explainer: [
    "A one-on-one arcade fighter in the old style: two corners, best of three rounds, uppercuts, sweeps and a special move each. An arena is a Calimero context, and it replicates between the two fighters’ own nodes — there is no game server anywhere.",
    "Movement streams sixty times a second over ephemeral presence, which never touches storage. Every action you finish — a punch, a kick, a jump, a block — is one contract transaction on your node, gossiped to your opponent’s, and the health bars are what the contract derives from those transactions. The arena shows the count as you fight.",
  ],
  features: [
    {
      icon: Zap,
      title: "Every blow is a transaction",
      body: "A fight is hundreds of signed contract calls a minute between two machines, with the throughput and confirm time on screen.",
    },
    {
      icon: CloudX,
      title: "No game server",
      body: "An arena is a context. Two nodes hold the same fight, and movement travels peer to peer over presence.",
    },
    {
      icon: Target,
      title: "Health nobody writes down",
      body: "The contract derives health, rounds and the winner from the blows themselves, so the score cannot disagree with the fight.",
    },
    {
      icon: LockCheck,
      title: "Blows are owned",
      body: "Every action is stamped with its author by core, so a player can only ever land blows for themselves.",
    },
    {
      icon: ExternalLink,
      title: "Invite by link",
      body: "One link opens the arena. No sign-up, no account — whoever opens it can take the open corner or watch.",
    },
  ],
  overview: {
    headline: "A fighting game where every punch is a transaction.",
    comparison: {
      heading: "Online fighting games, without the server in the middle",
      sub: "Two fighters, three rounds, health bars that drain. The difference is who holds the fight, and who keeps the score.",
      themLabel: "A typical online fighting game",
      rows: [
        { label: "Where the match lives", them: "On the publisher’s game server", us: "On your node and your opponent’s, nobody else’s" },
        { label: "Who keeps the score", them: "The server", us: "The contract, deriving health from every blow on both nodes" },
        { label: "Starting a match", them: "An account, then matchmaking", us: "One invite link. No sign-up, no email" },
        { label: "What a punch is", them: "A packet the server may or may not keep", us: "A signed transaction, executed and stored" },
        { label: "If the server goes away", them: "So does the game", us: "Your node still has every round" },
      ],
    },
    closing: { title: "Step into the arena", body: "Connect a node, or install the desktop app that bundles one, then send your opponent the link. Or warm up against the CPU first." },
  },
  faq: [
    {
      q: "Is every punch really a transaction?",
      a: "Yes. Each finished action — a punch, a kick, an uppercut, a jump, a block — is one call to the contract on your node, which executes it, stores it and gossips it to your opponent’s node. Walking is not: position streams over ephemeral presence, which is built for exactly that.",
    },
    {
      q: "Who decides whether a blow connected?",
      a: "The fighter who threw it — only their screen knows where their fist was. The contract bounds what a claim can be worth (fixed damage per move, chip damage when blocked) and stamps every row with its author, so you can only ever land blows for yourself.",
    },
    {
      q: "What if we both land the finishing blow at once?",
      a: "It is a double knock-out. Both nodes count the same blows, so both reach the same verdict, and the round scores for nobody.",
    },
    {
      q: "Can I play without a node?",
      a: "Practice mode runs entirely in your browser against a CPU opponent. Nothing in practice is a transaction — that needs an arena and an opponent.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "An arena is a Calimero context. There is no game server: each fighter’s own node runs the contract, stores every blow thrown, and replicates them to the other. Health, rounds and the winner are derived by the contract from those blows, so both nodes reach the same verdict.",
      ],
      concepts: [
        { term: "Namespace", def: "A dojo. You create one, invite the people you fight, and every arena inside it is open to them without another invitation." },
        { term: "Context", def: "An arena. It holds the two corners and every action either fighter has taken, across as many matches as you like." },
        { term: "Corner", def: "Left or right. The first person to claim a corner holds it, and once both fighters have acted against each other the corners lock." },
        { term: "Action", def: "One finished move — a punch, kick, uppercut, sweep, flying kick, special, jump or block — and one contract transaction." },
        { term: "Presence", def: "Where your fighter stands, fifteen times a second, over the node’s ephemeral channel. Never stored, never a transaction." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node. The Calimero desktop app bundles one; if you run your own, enter its URL in the same popup." },
        { title: "Open an arena", body: "A new arena is a context in a namespace you own. Joining someone else’s means opening their invite link." },
        { title: "Pick a fighter and a corner", body: "Choose Kinetic, Cryo, Inferno or Jinzo and take an open corner. The fight starts when both corners are taken and both fighters are in the arena." },
        { title: "Fight", body: "A and D move, W jumps, S crouches. J punches, K kicks, L blocks and I throws your special. Crouch with J for an uppercut, crouch with K for a sweep, and K in the air for a flying kick." },
      ],
    },
    {
      id: "sharing",
      heading: "Fighting someone else",
      paragraphs: [
        "Invitations are links. There is no account, no email address and no sign-up: opening the link and connecting a node is the whole of joining, and whoever opens it can take the open corner or watch.",
        "The invitation admits someone to the namespace the arena lives in, so one link is enough for every arena in that namespace.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Every action, keyed by fighter, match and round: what it was, whether it connected, whether it was blocked, and the opponent its author saw.",
        "The two corners, each recording who claimed it and when.",
        "Rematch claims. A new match starts when a fighter in a corner calls one after the last match ended.",
        "Never health. Health, round wins, the winner and a flawless victory are derived from the actions on every read, so nothing can write a score that disagrees with the fight.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "A transaction is refused", def: "A blow written for a round that has already ended, or after the match is over, is refused by the contract. It shows in the chain panel and changes nothing." },
        { term: "The other fighter looks away", def: "Their presence stream stopped for a few seconds. The fight waits for them; their blows count when their node reconnects." },
        { term: "The health bars jump back", def: "A blow your screen saw over presence never reached the contract. The bars settle on what the contract counts." },
        { term: "The invite link does nothing", def: "An invitation is tied to the namespace that minted it. Ask for a fresh one rather than reusing an old link." },
      ],
    },
  ],
  previewSteps: [
    { title: "An arena that is a context", body: "Two corners and every blow thrown, replicated between the two fighters’ own nodes. Nothing in the middle, and nothing to host." },
    { title: "Movement over presence", body: "Where each fighter stands streams fifteen times a second over ephemeral presence — fast, encrypted, and never stored." },
    { title: "Blows are transactions", body: "Every finished punch, kick, jump and block is a signed contract call on your node, gossiped to your opponent’s." },
    { title: "The score is derived", body: "Nobody writes down \"K.O.\": both nodes count the same blows and reach the same verdict, round after round." },
  ],
  loginPopup: LoginPopup,
};
