// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, createWorkspace, createIssue, uniqueName } from './helpers';

test.describe(`team member: search issues by title client-side`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
    await createWorkspace(page);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`typing a query narrows the list to matching issues; clearing it restores both`, async ({ page }) => {
    const titleA = uniqueName('zephyr-alpha');
    const titleB = uniqueName('quartz-beta');

    await createIssue(page, { title: titleA });
    await expect(page.getByTestId('item-issue').filter({ hasText: titleA })).toBeVisible({ timeout: 10_000 });

    await createIssue(page, { title: titleB });
    await expect(page.getByTestId('item-issue').filter({ hasText: titleB })).toBeVisible({ timeout: 10_000 });

    const search = page.getByTestId('search-input');
    await search.fill('zephyr-alpha');

    await expect(page.getByTestId('item-issue').filter({ hasText: titleA })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByTestId('item-issue').filter({ hasText: titleB })).toHaveCount(0);

    await search.fill('');

    await expect(page.getByTestId('item-issue').filter({ hasText: titleA })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByTestId('item-issue').filter({ hasText: titleB })).toBeVisible({ timeout: 5_000 });
  });
});
