/**
 * Landing content for Hyperfeed.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { Eye, MessageCircle, ShieldCheck, Zap } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Hyperfeed",
  packageId: "com.calimero.hyperfeed",
  tagline: "One feed for your agent and your apps: every action your agent took on your behalf, with its provenance, beside every notification the apps it uses sent you. Approvals, undo and per-app agent permissions live in a context only you write to.",
  dir: "hyperfeed",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Only you write to your feed", "Every action has provenance", "Your rules, checked first"],
  explainer: [
    "Hyperfeed is one feed of everything an agent did on your behalf, beside every notification the apps it uses sent you. Each action carries its app, its method and its reason, plus the warrant’s intent hash when it acted through one, and a row can be approved, answered or undone where it lands.",
    "The feed is a Calimero context on your own node that only you write to. Your agent checks your rules there before it writes anywhere else, reports what it did, and carries out what you decide. While the app is open it also watches your other contexts and records what they emit as notifications.",
  ],
  features: [
    {
      icon: Zap,
      title: "Everything your agent did",
      body: "Every action it took or wants to take, grouped into chains you can expand into the whole flow.",
    },
    {
      icon: MessageCircle,
      title: "Resolve it where it lands",
      body: "Reply to a chat, pick an option or confirm in place. Your agent carries it out and reports back.",
    },
    {
      icon: ShieldCheck,
      title: "Your rules, per app",
      body: "Act, ask first, read only or off for each app, guards that always ask, and one switch to pause it.",
    },
    {
      icon: Eye,
      title: "Provenance on every row",
      body: "Which app, which method and why, and the warrant’s intent hash when it signed one as you.",
    },
  ],
  overview: {
    headline: "Everything your agent did, and everything your apps sent you. One feed, on your node.",
    comparison: {
      heading: "An agent that answers to you",
      sub: "Letting an agent act in your apps usually means trusting a log someone else keeps. Here the log, the rules and the approvals are yours.",
      themLabel: "A typical agent with app access",
      rows: [
        { label: "What it did on your behalf", them: "Scattered across each app, if logged at all", us: "One feed: every action with its app, method and reason" },
        { label: "What it may do", them: "Whatever the token allows", us: "Your rules per app: act, ask first, read only or off" },
        { label: "Signing, money, new contacts", them: "Same as everything else", us: "Guards that always ask you, whatever the app allows" },
        { label: "Answering a message", them: "Open the app, find the thread, reply", us: "Reply, pick or confirm right in the feed; the agent delivers it" },
        { label: "Where it is kept", them: "In the agent vendor’s database", us: "In a context on your own node that only you write to" },
      ],
    },
    closing: { title: "Open your feed", body: "Connect your node and create your feed. Then point your agent at it: mero-bot plugs in as is." },
  },
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "Your feed is one Calimero context. You create it, and only you write to it: your devices, and your agent, which writes as your node. Nothing in it is shared with anyone else.",
      ],
      concepts: [
        { term: "Action", def: "Something your agent did, or wants to do: an app, a method, a title and its reason, and the warrant’s intent hash when it acted through one. A proposal waits for you; an outcome is reported after the fact." },
        { term: "Notification", def: "Something one of your apps emitted, recorded by your client as it watches your other contexts. Each carries a dedupe key, so two devices watching the same stream record it once." },
        { term: "Chain", def: "The rows that happened because of one another: a mention, the agent’s proposal in answer to it, your decision, the outcome. The feed shows one row per chain, led by whatever needs you." },
        { term: "Ask", def: "How a row is answered in place: reply with text, choose one of a few options, or confirm with one button." },
        { term: "Policy", def: "What your agent may do in one app: act, ask first, read only, or off. An app you never set asks first." },
        { term: "Guard", def: "A kind of action that always needs you, whatever the app’s policy: signing, money, new contacts and deleting are on until you turn them off." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      paragraphs: [
        "To look around first, open /demo: the same screens against a feed kept in your browser, with a pretend agent that carries out what you decide. No node needed.",
      ],
      steps: [
        { title: "Connect a node", body: "Press Connect to node and sign in on your node." },
        { title: "Create your feed", body: "One button makes the context. Notifications from your other contexts start arriving while the app is open." },
        { title: "Set your rules", body: "On Controls, choose what your agent may do in each app, and which guards always ask you." },
        { title: "Connect your agent", body: "Run mero-bot against the same node. It checks your rules here, reports what it does, and carries out what you decide." },
      ],
    },
    {
      id: "sharing",
      heading: "Who can see it",
      paragraphs: [
        "You, on your own devices. The feed is a context with one member, and every write checks that it comes from the account that created it.",
        "That check runs in the contract, so it binds nodes running this code. A feed is meant to have no other member, so there is no other writer to defend against.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Actions and notifications in two maps keyed by id. Each keeps its full history of steps, merged as a union, so every device shows the same flow in the same order.",
        "Your policy per app, your guards and the pause switch, each last-writer-wins.",
        "Notification keys follow the source context’s state changes, so a repeat within ten seconds is the same event seen twice and is recorded once.",
        "Nothing from your other apps but what their events said: a title, a sender, a short body.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "A notification never arrived", def: "Notifications are recorded by a client that is watching: this app while it is open, or mero-bot while it runs. Events emitted while neither was running are not replayed." },
        { term: "You approved and nothing happened", def: "Your agent carries decisions out. Check that mero-bot is running against this node; it picks up approvals it missed when it starts." },
        { term: "Your agent asked when it could have acted", def: "A guard is on for that kind of action, the app is set to ask first, or the agent is paused. Controls shows all three." },
      ],
    },
  ],
  previewSteps: [
    { title: "A mention arrives", body: "Maya mentions you in #launch. The event is recorded in your feed from your own node." },
    { title: "Your agent did something", body: "It posted your stand-up, where your rules let it act, with its reason attached." },
    { title: "It asks before booking", body: "Calendar is set to ask first, so the agent proposes two slots instead of booking one." },
    { title: "You pick, it carries it out", body: "One tap picks the slot. The agent books it and reports back in the same chain." },
  ],
  loginPopup: LoginPopup,
};
