/**
 * Landing content for Mero Calendar.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { EyeOff, Grid, HeartCheck, Moon, Shield } from '@calimero-network/mero-icons';

import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Calendar",
  packageId: "com.calimero.mero-calendar",
  tagline: "A collaborative, peer-to-peer calendar on the Calimero network. Shared team calendars and private events — your schedule on your own nodes.",
  dir: "mero-calendar",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Teams are namespaces", "Private events never sync", "Light and dark"],
  explainer: [
    "A shared calendar for a team that does not want its schedule sitting in someone else’s cloud. A team is a Calimero namespace, so the people in it are exactly the people you invited, and the calendar lives on their nodes and yours.",
    "Shared events are owner-gated, so a member sees what they own or were invited to rather than everything. Private events use node-local storage and never replicate at all — they exist on your machine and nowhere else.",
  ],
  features: [
    {
      icon: Grid,
      title: "Teams are namespaces",
      body: "Everyone in the namespace syncs the same calendar. Membership is the access model.",
    },
    {
      icon: Shield,
      title: "Owner-gated shared events",
      body: "Members see events they own or were invited to, not the whole team’s diary by default.",
    },
    {
      icon: EyeOff,
      title: "Genuinely private events",
      body: "Node-local storage that never replicates. Not \"private\" as a flag on a shared record.",
    },
    {
      icon: Moon,
      title: "Light and dark themes",
      body: "With an accessible palette, because a calendar is something people stare at all day.",
    },
    {
      icon: HeartCheck,
      title: "Readable identities",
      body: "Display names instead of key hashes, so a shared calendar reads like one.",
    },
  ],
};
