/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Comment {
  id: string;
  issue_id: string;
  author: string;
  body: string;
  created_at: number;
  edited_at: number;
}

export interface CommentView {
  id: string;
  issue_id: string;
  author: string;
  body: string;
  created_at: number;
  edited_at: number | null;
}

export interface Event_CommentAdded {
  id: string;
  issue_id: string;
}

export interface Event_CommentDeleted {
  id: string;
}

export interface Event_CommentEdited {
  id: string;
}

export interface Event_IssueAssigneeChanged {
  id: string;
}

export interface Event_IssueCreated {
  id: string;
  created_by: string;
}

export interface Event_IssueDeleted {
  id: string;
}

export interface Event_IssueEdited {
  id: string;
}

export interface Event_IssueLabelsChanged {
  id: string;
}

export interface Event_IssuePriorityChanged {
  id: string;
  priority: string;
}

export interface Event_IssueStatusChanged {
  id: string;
  status: string;
}

export interface Event_RepoUrlChanged {
  url: string;
}

export interface Issue {
  id: string;
  title: string;
  summary: string;
  impact: string;
  repro: string;
  resolution_criteria: string;
  status: string;
  priority: string;
  assignee: string;
  created_by: string;
  created_at: number;
}

export interface IssueDetail {
  issue: IssueView;
  comments: CommentView[];
}

export interface IssueTracker {
  issues: Record<string, Issue>;
  comments: Record<string, Comment>;
  labels: Record<string, number>;
  repo_url: string;
}

export interface IssueView {
  id: string;
  title: string;
  summary: string;
  impact: string;
  repro: string;
  resolution_criteria: string;
  status: string;
  priority: string;
  assignee: string | null;
  labels: string[];
  created_by: string;
  created_at: number;
}

export interface RepoInfo {
  repo_url: string;
}

export interface StatusCount {
  status: string;
  count: number;
}












export type AbiEvent =
  | { name: "IssueCreated"; payload: Event_IssueCreated }
  | { name: "IssueEdited"; payload: Event_IssueEdited }
  | { name: "IssueDeleted"; payload: Event_IssueDeleted }
  | { name: "IssueStatusChanged"; payload: Event_IssueStatusChanged }
  | { name: "IssuePriorityChanged"; payload: Event_IssuePriorityChanged }
  | { name: "IssueAssigneeChanged"; payload: Event_IssueAssigneeChanged }
  | { name: "IssueLabelsChanged"; payload: Event_IssueLabelsChanged }
  | { name: "CommentAdded"; payload: Event_CommentAdded }
  | { name: "CommentEdited"; payload: Event_CommentEdited }
  | { name: "CommentDeleted"; payload: Event_CommentDeleted }
  | { name: "RepoUrlChanged"; payload: Event_RepoUrlChanged }
;


export class IssueTrackerClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_repo_url
   */
  public async setRepoUrl(params: { url: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_repo_url', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_repo_info
   */
  public async getRepoInfo(): Promise<RepoInfo> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_repo_info', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as RepoInfo;
  }

  /**
   * create_issue
   */
  public async createIssue(params: { title: string; summary: string; impact: string; repro: string; resolution_criteria: string; priority: string; labels: string[] | null }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_issue', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * set_status
   */
  public async setStatus(params: { issue_id: string; status: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_status', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_summary
   */
  public async setSummary(params: { issue_id: string; summary: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_summary', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_impact
   */
  public async setImpact(params: { issue_id: string; impact: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_impact', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_repro
   */
  public async setRepro(params: { issue_id: string; repro: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_repro', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_resolution_criteria
   */
  public async setResolutionCriteria(params: { issue_id: string; resolution_criteria: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_resolution_criteria', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_priority
   */
  public async setPriority(params: { issue_id: string; priority: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_priority', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * set_assignee
   */
  public async setAssignee(params: { issue_id: string; assignee: string | null }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_assignee', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * add_label
   */
  public async addLabel(params: { issue_id: string; label: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_label', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * remove_label
   */
  public async removeLabel(params: { issue_id: string; label: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'remove_label', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * list_issues
   */
  public async listIssues(params: { status: string | null; assignee: string | null; label: string | null }): Promise<IssueView[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_issues', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as IssueView[];
  }

  /**
   * get_issue
   */
  public async getIssue(params: { issue_id: string }): Promise<IssueDetail> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_issue', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as IssueDetail;
  }

  /**
   * get_status_counts
   */
  public async getStatusCounts(): Promise<StatusCount[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_status_counts', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as StatusCount[];
  }

  /**
   * add_comment
   */
  public async addComment(params: { issue_id: string; body: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * edit_comment
   */
  public async editComment(params: { comment_id: string; new_body: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_comment
   */
  public async deleteComment(params: { comment_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_issue
   */
  public async deleteIssue(params: { issue_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_issue', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

}