/**
 * Landing content for Mero Drive Docs.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { Eye, FileText, Folder, Shield, Table } from '@calimero-network/mero-icons';

import Animation from './animation';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Drive Docs",
  packageId: "com.calimero.mero-drive-docs",
  tagline: "Namespace-based document workspace - registry + docs multi-service bundle.",
  dir: "mero-drive",
  markSrc: "/icons/icon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Folders are contexts", "Rich-text editing", "Private by default"],
  explainer: [
    "A document workspace — folders, rich-text documents, and the tags you need to find them again six months later. Built as a multi-service bundle: a registry service holds the folder tree for a namespace, and each folder is its own context holding its documents.",
    "That structure is the point. A folder’s documents replicate only to the people who have that folder, so sharing one project does not hand over the whole workspace.",
  ],
  features: [
    {
      icon: Folder,
      title: "Folders are contexts",
      body: "Each folder’s documents live in their own context, so access is per folder rather than all-or-nothing.",
    },
    {
      icon: FileText,
      title: "Rich-text documents",
      body: "A real editor with formatting, headings and lists, syncing as you type.",
    },
    {
      icon: Table,
      title: "Tags and archive",
      body: "Organise by tag and retire what is finished without deleting anything.",
    },
    {
      icon: Shield,
      title: "Namespace-scoped",
      body: "The workspace is a namespace you control. Membership is how access works.",
    },
    {
      icon: Eye,
      title: "Per-folder visibility",
      body: "Decide what is shared and what stays yours, folder by folder.",
    },
  ],
  animation: Animation,
};
