/**
 * Landing content for Mero Sheets.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { BarChart, Download, FileText, Lock, Table, Zap } from '@calimero-network/mero-icons';

import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Sheets",
  packageId: "com.calimero.mero-sheets",
  tagline: "Collaborative peer-to-peer spreadsheet with live cursors, multiple sheet tabs, formula autocomplete, a built-in function help section, and download support",
  dir: "mero-sheets",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Live cursors", "Formulas recompute for all peers", "Sheet on your node"],
  explainer: [
    "A collaborative spreadsheet where you can see everyone’s cursor and nobody can see your data except the people you invited. The sheet lives in a Calimero context on your own node.",
    "Formulas are stored raw and re-evaluated for every peer whenever a cell they reference changes, so nobody is looking at a stale total — which is the failure that makes shared spreadsheets untrustworthy in the first place.",
  ],
  features: [
    {
      icon: Lock,
      title: "Truly private sheets",
      body: "The data lives in a context you control. It never passes through a central server.",
    },
    {
      icon: Zap,
      title: "Live cursors",
      body: "Every collaborator in their own colour, so you can see who is about to overwrite what.",
    },
    {
      icon: BarChart,
      title: "Formulas that always compute",
      body: "SUM, AVERAGE, MIN, MAX, COUNT and IF, re-evaluated per peer whenever a referenced cell changes.",
    },
    {
      icon: Table,
      title: "Multiple sheet tabs",
      body: "Split a workbook the way you would expect, with tabs that sync like everything else.",
    },
    {
      icon: FileText,
      title: "Formula autocomplete",
      body: "With a built-in function reference, so you do not have to remember the argument order.",
    },
    {
      icon: Download,
      title: "Download your data",
      body: "Export whenever you want. Nothing here is designed to keep your numbers hostage.",
    },
  ],
};
