/**
 * Landing content for Mero Models.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { CloudX, Cube3D, LockCheck, Target, Upload } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Models",
  packageId: "com.calimero.mero-models",
  tagline: "Blender-style 3D modelling with no server. A scene is a Calimero context: objects, meshes and materials replicate peer to peer between the members' own nodes, and everyone edits the same model at once.",
  dir: "mero-models",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["No server holds your models", "Editing enforced by the contract", "OBJ · STL · glTF in and out"],
  explainer: [
    "A Blender-style modeller in the browser: add primitives, move, rotate and scale them with a gizmo, drop into edit mode to push vertices around and extrude faces, give things materials and lights, and export the result as glTF, OBJ or STL. A scene is a Calimero context, and it replicates between its members’ own nodes.",
    "Everyone in the scene sees every change as it lands, and sees each other: what the others have selected and where they are looking from streams over ephemeral presence, which never touches storage. Who may change the model is decided by the scene’s admin and enforced by the contract on every node.",
  ],
  features: [
    {
      icon: Cube3D,
      title: "A real modeller",
      body: "Primitives, meshes, hierarchy, a transform gizmo with snapping, edit mode with extrude and merge, undo and redo, and the shortcuts you already know.",
    },
    {
      icon: CloudX,
      title: "No server holds the model",
      body: "A scene is a context. Every member’s node keeps the whole scene, and edits travel peer to peer.",
    },
    {
      icon: Target,
      title: "Live together",
      body: "See who is in the scene, what they have selected and where their camera is, and jump to their view with one click.",
    },
    {
      icon: LockCheck,
      title: "Editors, enforced",
      body: "Anyone invited can watch; only editors the admin names can change the scene, and every node refuses anyone else’s write.",
    },
    {
      icon: Upload,
      title: "Bring models in, take them out",
      body: "Import OBJ, STL and glTF, export glTF, OBJ and STL, or save the whole scene as a file.",
    },
  ],
  overview: {
    headline: "A 3D modeller where the scene lives on your nodes.",
    comparison: {
      heading: "Collaborative 3D, without the cloud in the middle",
      sub: "Primitives, meshes, materials and lights in a viewport you already know how to drive. The difference is who holds the model.",
      themLabel: "A typical cloud 3D tool",
      rows: [
        { label: "Where the model lives", them: "In the vendor’s cloud", us: "On every member’s own node, nobody else’s" },
        { label: "Editing together", them: "Through the vendor’s servers", us: "Peer to peer, merging as a CRDT" },
        { label: "Who may change it", them: "Whatever the vendor’s backend allows", us: "Editors the scene’s admin names, enforced on every node" },
        { label: "Getting your work out", them: "An export button, while the service lasts", us: "glTF, OBJ and STL out of the box, and the scene is already on your disk" },
        { label: "If the service goes away", them: "Your models may go with it", us: "Your node still has every object and every vertex" },
      ],
    },
    closing: { title: "Start a scene", body: "Connect a node, or install the desktop app that bundles one, then send the people you build with the link." },
  },
  faq: [
    {
      q: "What happens when two people move the same object?",
      a: "Each object is one record, and the merge keeps one person’s write whole — the same one on every node. You never end up with a cube that took its position from one person and its colour from the other.",
    },
    {
      q: "How big can a model be?",
      a: "A scene holds up to 2,000 objects, and a single mesh up to 30,000 vertices and 60,000 triangles. An import above that is simplified to fit, and the app says so.",
    },
    {
      q: "Can someone I invite change my scene?",
      a: "Not unless you let them. An invitation lets someone open the scene and watch; the scene’s admin ticks Can edit for the people who may change it, and the contract enforces that on every node, not just in the app.",
    },
    {
      q: "Does moving the camera send anything?",
      a: "Only presence: where you are looking from and what you have selected, over the node’s ephemeral channel. It is never stored and never a transaction. Moving an object is a transaction, sent once when you let go.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "A 3D scene is a Calimero context. There is no server keeping the model: every member’s own node runs the contract, holds every object and every vertex, and replicates changes to the others.",
      ],
      concepts: [
        { term: "Namespace", def: "A studio. You create one, invite the people you build with, and every scene inside it is open to them without another invitation." },
        { term: "Context", def: "A scene. It holds the objects, their meshes, the world settings and who may edit." },
        { term: "Object", def: "One thing in the outliner: a primitive, a mesh, a light or an empty, with a transform, a material and a parent." },
        { term: "Mesh", def: "The vertices and triangles of an edited or imported shape, stored apart from the object so moving it never rewrites them." },
        { term: "Editor", def: "Someone the scene’s admin has allowed to change it. Everyone else in the namespace can open the scene and watch." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node. The Calimero desktop app bundles one; if you run your own, enter its URL in the same popup." },
        { title: "Start a scene", body: "Name it and press New scene. That creates a namespace you own and a scene inside it, with you as its admin." },
        { title: "Build", body: "Shift+A adds a primitive. Drag the gizmo to move it; G, R and S switch between move, rotate and scale, Tab edits vertices, and Ctrl+Z undoes." },
        { title: "Invite", body: "Share mints a link. Whoever opens it can watch at once; tick Can edit beside their name to let them build too." },
      ],
    },
    {
      id: "sharing",
      heading: "Building with someone else",
      paragraphs: [
        "Invitations are links. There is no account and no sign-up: opening the link and connecting a node is the whole of joining.",
        "The others in the scene appear as coloured avatars. Their selections are outlined in their colour, their camera is a small marker in the viewport, and clicking an avatar takes you to their view.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "One record per object: its name, kind, parent, position, rotation, scale, visibility, material and light settings. Two people changing the same object resolve to one of their writes, whole.",
        "One record per edited or imported mesh: its vertex positions and triangles, up to 30,000 vertices.",
        "The scene’s name, background and ambient light, and each member’s display name.",
        "Who may edit, as a role the admin grants. The scene’s collections enforce it on every node, so a viewer’s write is refused everywhere, not just in their app.",
        "Not stored: cameras and selections. They stream over ephemeral presence and vanish when you leave.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "Your edit is refused", def: "You are a viewer. The admin can tick Can edit beside your name in Share." },
        { term: "An object jumped back", def: "Someone else moved it at the same moment, and their write is the one every node kept. Move it again." },
        { term: "An import was simplified", def: "A mesh over 30,000 vertices is decimated to fit, and the status bar says by how much." },
        { term: "The invite link does nothing", def: "An invitation is tied to the namespace that minted it. Ask for a fresh one rather than reusing an old link." },
      ],
    },
  ],
  previewSteps: [
    { title: "A scene that is a context", body: "Objects, meshes and materials replicated between members’ own nodes. Nothing in the middle, and nothing to host." },
    { title: "Edit like a modeller", body: "Primitives, a gizmo, edit mode with extrude, and the shortcuts you already know." },
    { title: "Together, live", body: "Every change lands on every node as it is made, and you can see where the others are looking." },
    { title: "Out in standard formats", body: "glTF, OBJ and STL, whenever you want them." },
  ],
  loginPopup: LoginPopup,
};
