/**
 * Landing content for Mero Books.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { BarChart, Clock, FileCheck, Refresh, Shield, Target } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Books",
  packageId: "com.calimero.mero-books",
  tagline: "Accounting for small businesses - invoices, bills, bank reconciliation and reports, on your own nodes",
  dir: "mero-books",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  themeStorageKey: "app:theme",
  trust: ["Double-entry ledger", "Books on your nodes", "No per-seat vendor"],
  explainer: [
    "Accounting for a small business, with the parts a bookkeeper actually uses every week: invoices and bills, payments against them, spend and receive money, bank statement reconciliation, manual journals, and the reports an accountant asks for at year end. What tools like Xero are used for day to day.",
    "The books live in a Calimero context your team shares, replicated between your own nodes. Every report is derived from posted transactions on read, and a posted transaction can only be voided, never edited — on every node, not just in the UI.",
  ],
  features: [
    {
      icon: FileCheck,
      title: "Invoices and bills",
      body: "Line items, tax inclusive or exclusive, numbered on approval, printable, and paid in part or in full.",
    },
    {
      icon: Refresh,
      title: "Bank reconciliation",
      body: "Import your bank’s CSV, accept the suggested matches with one click, or code a line straight to an account.",
    },
    {
      icon: BarChart,
      title: "Reports",
      body: "Profit and loss, balance sheet, trial balance, aged receivables and payables, and the tax return — all exportable.",
    },
    {
      icon: Target,
      title: "A real ledger",
      body: "Double entry under everything, with a chart of accounts, manual journals and a lock date for filed periods.",
    },
    {
      icon: Clock,
      title: "Know what is owed",
      body: "The dashboard shows what customers owe, what is overdue, what you owe suppliers, and cash in and out.",
    },
    {
      icon: Shield,
      title: "Your numbers stay yours",
      body: "Your books replicate between your team’s nodes. There is no vendor database holding your finances.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "The model is the one every set of books shares: a chart of accounts, documents that post to it, and reports that add it up.",
      ],
      concepts: [
        { term: "Namespace", def: "Your team or your practice. Its members are the people who can see and keep the books." },
        { term: "Organisation", def: "One set of books — a company, or a client you keep the accounts for — and one Calimero context." },
        { term: "Chart of accounts", def: "The accounts everything is coded to: bank, receivables, sales, expenses, tax and equity. A new organisation starts with a standard chart you can edit." },
        { term: "Draft and approved", def: "A draft invoice or bill can be edited by anyone. Approving it freezes a write-once copy and posts it to the ledger; after that it can be paid or voided, never edited." },
        { term: "Void", def: "The reversal of a posted record. Its entries leave the ledger, the record and who voided it stay in the history, and nothing un-voids." },
        { term: "Reconciliation", def: "Matching each line of your bank statement to the payment or transaction in the books that it records." },
        { term: "Lock date", def: "Nothing dated on or before it can be posted or voided — for a filed tax period or a closed year." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node and pick your node in the popup." },
        { title: "Create a workspace and an organisation", body: "A workspace for the team, then an organisation with its currency. Set the financial year end and what tax is called under Settings." },
        { title: "Invoice a customer", body: "Sales → New invoice. Approve it to give it a number and post it." },
        { title: "Reconcile the bank", body: "Bank → your account → Import a statement, then accept the matches or code the rest." },
      ],
    },
    {
      id: "sharing",
      heading: "Keeping books together",
      paragraphs: [
        "Everyone in the workspace sees the same books as they change. Two people editing different fields of one draft both keep their edit.",
        "Approvals, payments, spend and receive money, journals and voids are written once by the member who posted them, and that member is recorded by the storage layer itself — the audit trail on every document says who did what.",
        "Importing the same bank statement on two machines produces one set of lines: each line’s id is derived from its content.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Accounts, tax rates, contacts, draft documents and statement lines as maps of per-field registers in the organisation’s context.",
        "Approvals, payments, bank transactions, journals and voids in write-once collections: no node accepts an edit or a removal of one.",
        "No balances. The ledger, every report, invoice numbers and whether a statement line is reconciled are derived from the posted records on read.",
        "Money as integer cents and tax rates as basis points, never floats, so every node computes identical totals.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "An invoice cannot be voided", def: "It has payments. Remove the payments first, then void it." },
        { term: "Nothing posts for an old date", def: "The books are locked through that date. Unlock them under Settings if the change is really needed." },
        { term: "“Conflicting approvals” on a document", def: "Two members filed an approval for it, which only a modified node can do. The earliest is used; void and re-enter it if it is wrong." },
      ],
    },
  ],
  previewSteps: [
    { title: "The dashboard", body: "Bank balances, what customers owe, what is overdue and what you owe — derived from the ledger, nothing stored as a total." },
    { title: "An invoice is approved", body: "Its lines freeze into a write-once record and it takes the next number. Receivables and sales move together." },
    { title: "The bank statement arrives", body: "Imported lines line up against the payments already recorded; one click reconciles each." },
    { title: "The year-end reports", body: "Profit and loss, balance sheet and trial balance, which balances by construction." },
  ],
  loginPopup: LoginPopup,
};
