/**
 * Landing page contract for Mero Calendar — all three pages of it.
 *
 * GENERATED by `pnpm landing:generate`. Do not edit — `pnpm landing:check`
 * fails CI on drift. The assertions live in scripts/landing/generate.mjs.
 */
import { test, expect } from '@playwright/test';

const DOC_SECTIONS = ["concepts","start","sharing","storage","offline","trouble"];

test.describe('Mero Calendar landing page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('hero names the app and its tagline', async ({ page }) => {
    await expect(page.getByRole('heading', { level: 1, name: "Mero Calendar" })).toBeVisible();
    await expect(page.locator('.cal-lp-lede')).toBeVisible();
  });

  test('shows the availability badge', async ({ page }) => {
    // Scoped to the badge row on purpose: the same words legitimately appear
    // again in the trust strip, and an unscoped getByText is a strict-mode
    // violation the moment an app says both.
    await expect(
      page.locator('.cal-lp-badge').filter({ hasText: "Web + Desktop" }),
    ).toHaveCount(1);
  });

  test('the overview is the pitch, not the manual', async ({ page }) => {
    // Deliberately asserted without scrolling. A reveal that gates on an
    // IntersectionObserver renders these blank in a headless capture, which is
    // the bug this fleet hit twice.
    await expect(page.locator('#features')).toBeVisible();
    await expect(page.locator('.cal-lp-feature')).toHaveCount(5);
    // The explainer, the four steps and the FAQ moved to /docs. Finding them
    // here again would mean the split silently un-split.
    await expect(page.locator('#about')).toHaveCount(0);
    await expect(page.locator('#faq')).toHaveCount(0);
  });

  test('defaults to light, even when the OS asks for dark', async ({ page }) => {
    // The page is deliberately NOT prefers-color-scheme aware: a landing page
    // is the first thing a stranger sees, and the same page in a screenshot, a
    // review and a share card. Dark is reachable only by clicking the toggle.
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.reload();
    const root = page.locator('.cal-lp-root');
    await expect(root).toHaveAttribute('data-cal-lp-theme', 'light');
    // The attribute states the intent; this is what actually got painted. A
    // stray prefers-color-scheme rule anywhere in landing.css would pass the
    // line above and fail this one.
    await expect(root).toHaveCSS('background-color', 'rgb(252, 252, 252)');

    // ⚠️ And again on a REPEAT visit, which is a different code path and the
    // one that was actually broken. mero-calendar, mero-meet, mero-sheets and
    // mero-issue-tracker each seed their own ThemeProvider from
    // prefers-color-scheme and then WRITE that to localStorage in a mount
    // effect — so a one-shot check sees light (the effect has not run yet)
    // while every visit after it is dark.
    await page.reload();
    await expect(root).toHaveAttribute('data-cal-lp-theme', 'light');
    await expect(root).toHaveCSS('background-color', 'rgb(252, 252, 252)');
  });

  test('the theme toggle lives in the footer and flips both ways', async ({ page }) => {
    const toggle = page.getByTestId('theme-toggle');
    // In the footer, not the header. The header's job is to say what this is
    // and offer the way in; a colour preference is small print.
    await expect(page.locator('.cal-lp-footer').getByTestId('theme-toggle')).toHaveCount(1);
    await expect(page.locator('.cal-lp-header').getByTestId('theme-toggle')).toHaveCount(0);

    const root = page.locator('.cal-lp-root');
    await toggle.click();
    await expect(root).toHaveAttribute('data-cal-lp-theme', 'dark');
    await toggle.click();
    await expect(root).toHaveAttribute('data-cal-lp-theme', 'light');
  });

  // ── The three pages ─────────────────────────────────────────────────────
  test('the nav moves between the three pages, and the URL follows', async ({ page }) => {
    await page.getByRole('navigation').getByRole('link', { name: 'Docs' }).click();
    await expect(page).toHaveURL(/\/docs$/);
    await expect(page.locator('.cal-lp-root')).toHaveAttribute('data-cal-lp-view', 'docs');

    await page.getByRole('navigation').getByRole('link', { name: 'Preview' }).click();
    await expect(page).toHaveURL(/\/preview$/);
    await expect(page.locator('.cal-lp-root')).toHaveAttribute('data-cal-lp-view', 'preview');

    // Real history, not just state: the back button has to work or these are
    // tabs wearing a URL.
    await page.goBack();
    await expect(page).toHaveURL(/\/docs$/);
    await expect(page.locator('.cal-lp-root')).toHaveAttribute('data-cal-lp-view', 'docs');
  });

  test('/docs opens cold, as a shared link would', async ({ page }) => {
    // ⚠️ A COLD load, not a click. Clicking is client-side routing and proves
    // nothing about whether the app routes the path — an app whose catch-all
    // swallows /docs passes the nav test above and fails this one, which is
    // exactly what a shared link would hit.
    await page.goto('/docs');
    await expect(page.locator('.cal-lp-root')).toHaveAttribute('data-cal-lp-view', 'docs');
    await expect(page.getByRole('heading', { level: 2, name: 'What this is' })).toBeVisible();
    for (const id of DOC_SECTIONS) {
      await expect(page.locator(`#${id}`)).toBeVisible();
    }
    await expect(page.locator('#how')).toBeVisible();
    await expect(page.locator('#faq')).toBeVisible();
    await expect(page.locator('.cal-lp-step')).toHaveCount(8);
  });

  test('the docs page has a table of contents that points at real sections', async ({ page }) => {
    await page.goto('/docs');
    const links = page.locator('.cal-lp-toclink');
    await expect(links).toHaveCount(9);
    // Every entry must resolve to an element that exists — a TOC pointing at a
    // renamed section is worse than no TOC.
    const hrefs = await links.evaluateAll((els) => els.map((e) => e.getAttribute('href')));
    for (const href of hrefs) {
      await expect(page.locator(href)).toHaveCount(1);
    }
  });

  test('a FAQ answer opens', async ({ page }) => {
    await page.goto('/docs');
    const first = page.locator('.cal-lp-faqq').first();
    await expect(first).toHaveAttribute('aria-expanded', 'false');
    await first.click();
    await expect(first).toHaveAttribute('aria-expanded', 'true');
    await expect(page.locator('.cal-lp-faqa').first()).toBeVisible();
  });

  test('/preview opens cold and captions every beat', async ({ page }) => {
    await page.goto('/preview');
    await expect(page.locator('.cal-lp-root')).toHaveAttribute('data-cal-lp-view', 'preview');
    await expect(page.locator('.cal-lp-stage--big')).toBeVisible();
    await expect(page.locator('.cal-lp-a').first()).toBeAttached();
    await expect(page.locator('.cal-lp-beat')).toHaveCount(4);
  });


  // ── No more /login ──────────────────────────────────────────────────────
  test('the login page is gone, and its path lands on the front door', async ({ page }) => {
    // This app had a /login route whose whole content was a button the visitor
    // had already pressed to get there. The path stays as a redirect so a
    // bookmark is not a blank route.
    await page.goto('/login');
    await expect(page).toHaveURL(/\/$/);
    await expect(page.locator('.cal-lp-root')).toHaveAttribute('data-cal-lp-view', 'overview');
  });


  test('connecting does not navigate to another page', async ({ page }) => {
    const cta = page.locator('button').filter({ hasText: /^Connect to node$/ }).first();
    await expect(cta).toBeVisible();
    // ⚠️ Compared against the URL we are ACTUALLY on, not against the root.
    // mero-stream and mero-meet redirect / to a picker route and render the
    // landing from a guard, so they sit at /streams or /rooms while showing
    // this page — and an assertion hard-coded to the root fails there for a
    // button that behaved perfectly.
    const before = page.url();
    await cta.click();
    // The whole point of the change: what used to be a route is now something
    // that happens over the page you were already reading. True whether that
    // is the shared popup, mero-sign's sidebar, or a game's launcher.
    await expect(page).toHaveURL(before);
  });

  test('and the landing page stays put underneath it', async ({ page }) => {
    await page.locator('button').filter({ hasText: /^Connect to node$/ }).first().click();
    await expect(page.locator('.cal-lp-root')).toHaveAttribute('data-cal-lp-view', 'overview');
  });


  test('offers the desktop download', async ({ page }) => {
    await expect(
      page.locator('a[href="https://calimero.network/download"]').first(),
    ).toBeVisible();
  });

  // ── Mobile ──────────────────────────────────────────────────────────────
  // 320px is the narrowest phone still in use and 390 is the common one. Both,
  // because the header and the hero art break at different widths. Every view,
  // because they are three different layouts.
  for (const width of [390, 320]) {
    for (const path of ['/', '/docs', '/preview']) {
      test(`${path} does not scroll sideways on a ${width}px phone`, async ({ page }) => {
        await page.setViewportSize({ width, height: 780 });
        await page.goto(path);
        await expect(page.locator('.cal-lp-root')).toBeVisible();
        // Measured on the landing root as well as the document.
        //
        // ⚠️ The document alone is VACUOUS for the two canvas games: their
        // mount.tsx renders this page into a fixed, inset-0, overflow-y-auto
        // host, so nothing it contains can ever move
        // documentElement.scrollWidth and the assertion passes without looking.
        const overflow = await page.evaluate(() => {
          const root = document.querySelector('.cal-lp-root');
          const doc = document.documentElement;
          return Math.max(
            doc.scrollWidth - doc.clientWidth,
            root ? root.scrollWidth - root.clientWidth : 0,
            root?.parentElement
              ? root.parentElement.scrollWidth - root.parentElement.clientWidth
              : 0,
          );
        });
        expect(overflow).toBeLessThanOrEqual(1);
      });
    }
  }

  test('the brand never wraps under its own icon on a phone', async ({ page }) => {
    // `Mero Issue Tracker` used to wrap under the mark and double the sticky
    // header's height. The header itself is taller on a phone now — the nav
    // wraps onto its own row rather than disappearing, because it is the only
    // way to reach two of the three pages — so this measures the brand, which
    // is the thing that actually broke.
    await page.setViewportSize({ width: 360, height: 780 });
    const brand = page.locator('.cal-lp-brand');
    await expect(brand).toBeVisible();
    const box = await brand.boundingBox();
    expect(box?.height ?? 0).toBeLessThanOrEqual(34);
  });

  test('the nav survives a phone, rather than being hidden', async ({ page }) => {
    await page.setViewportSize({ width: 360, height: 780 });
    await expect(page.getByRole('navigation').getByRole('link', { name: 'Docs' })).toBeVisible();
  });

  test('the hero art is drawn to fit its frame on a phone', async ({ page }) => {
    // The animations position their parts in literal pixels against a 495px
    // stage, so an unscaled box writes its rows over each other inside a 328px
    // phone frame. useStageScale() is what stops that, and it is invisible in
    // a screenshot review until you measure it.
    await page.setViewportSize({ width: 360, height: 780 });
    const body = page.locator('.cal-lp-stagebody');
    await expect(body).toBeVisible();
    const art = page.locator('.cal-lp-a').first();
    await expect(art).toBeAttached();
    const [bodyBox, artBox] = await Promise.all([body.boundingBox(), art.boundingBox()]);
    // Rendered width, after the scale — within a pixel of the frame it sits in.
    expect(Math.abs((artBox?.width ?? 0) - (bodyBox?.width ?? 0))).toBeLessThanOrEqual(1.5);
  });
});
