/** @generated by manual implementation for docs app — DO NOT EDIT. */

import { CalimeroApp, Context, ExecutionResponse } from '@calimero-network/calimero-client';

// Generated types

export interface Document {
  id: string;
  title: string;
  content: string;
  author: string;
  created_at: number;
  updated_at: number;
  tags: string[];
  archived: boolean;
  folder_id: string | null;
}

export interface DocumentSummary {
  id: string;
  title: string;
  author: string;
  created_at: number;
  updated_at: number;
  tags: string[];
  archived: boolean;
  preview: string;
  folder_id: string | null;
}

export interface FolderResponse {
  id: string;
  name: string;
  parent_id: string | null;
  created_at: number;
  updated_at: number;
  color: string | null;
  document_count: number;
  subfolder_count: number;
}

export interface FolderTreeItem {
  id: string;
  name: string;
  parent_id: string | null;
  color: string | null;
  document_count: number;
  children: FolderTreeItem[];
}

export interface FolderRegistryEntry {
  context_id: string;
  name: string;
  color: string | null;
  created_at: number;
}

export type AbiEvent =
  | { name: 'DocumentCreated'; id: string; title: string; author: string }
  | { name: 'DocumentUpdated'; id: string; title: string; editor: string }
  | { name: 'DocumentDeleted'; id: string; title: string }
  | { name: 'DocumentArchived'; id: string; archived: boolean }
  | { name: 'DocumentMoved'; id: string; from_folder: string | null; to_folder: string | null }
  | { name: 'FolderCreated'; id: string; folder_name: string; parent_id: string | null }
  | { name: 'FolderUpdated'; id: string; folder_name: string }
  | { name: 'FolderDeleted'; id: string; folder_name: string }
  | { name: 'FolderMoved'; id: string; from_parent: string | null; to_parent: string | null }
  | { name: 'ContextNameSet'; contextName: string }
  | { name: 'FolderRegistered'; context_id: string; folderName: string }
  | { name: 'FolderNameUpdated'; context_id: string; folderName: string }
  | { name: 'FolderUnregistered'; context_id: string };

/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === 'string') {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || [],
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

export class AbiClient {
  private app: CalimeroApp;
  private context: Context | null = null;
  private contextId: string | undefined;

  constructor(app: CalimeroApp, contextId?: string) {
    this.app = app;
    this.contextId = contextId;
  }

  private async getContext(): Promise<Context> {
    if (this.context) return this.context;

    const contexts = await this.app.fetchContexts();

    if (this.contextId) {
      const found = contexts.find(c => c.contextId === this.contextId);
      if (!found) {
        throw new Error(`Context not found: ${this.contextId}`);
      }
      this.context = found;
      return this.context;
    }

    if (contexts.length === 0) {
      // Create a new context if none exists
      this.context = await this.app.createContext();
    } else {
      this.context = contexts[0];
    }
    return this.context;
  }

  private async execute(method: string, params: Record<string, unknown>): Promise<ExecutionResponse> {
    const context = await this.getContext();
    console.log(`[AbiClient.execute] method: ${method}, context:`, context, 'params:', JSON.stringify(params).substring(0, 200));
    const result = await this.app.execute(context, method, params);
    console.log(`[AbiClient.execute] ${method} result:`, result);
    return result;
  }

  /**
   * Create a new document
   */
  public async createDocument(params: {
    title: string;
    content: string;
    tags: string[];
    folder_id?: string | null;
  }): Promise<string> {
    const response = await this.execute('create_document', {
      title: params.title,
      content: params.content,
      tags: params.tags,
      folder_id: params.folder_id ?? null,
    });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Update document metadata (title, archived status)
   */
  public async updateDocumentMetadata(params: {
    id: string;
    title?: string | null;
    archived?: boolean | null;
  }): Promise<void> {
    const response = await this.execute('update_document_metadata', {
      doc_id: params.id,
      title: params.title,
      archived: params.archived,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Insert text at a specific position (RGA operation)
   */
  public async insertText(params: {
    id: string;
    position: number;
    text: string;
  }): Promise<void> {
    const response = await this.execute('insert_text', {
      doc_id: params.id,
      position: params.position,
      text: params.text,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Delete text in a range (RGA operation)
   */
  public async deleteText(params: {
    id: string;
    start: number;
    end: number;
  }): Promise<void> {
    const response = await this.execute('delete_text', {
      doc_id: params.id,
      start: params.start,
      end: params.end,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Replace text in a range (atomic delete + insert)
   */
  public async replaceText(params: {
    id: string;
    start: number;
    end: number;
    text: string;
  }): Promise<void> {
    const response = await this.execute('replace_text', {
      doc_id: params.id,
      start: params.start,
      end: params.end,
      text: params.text,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Set the entire content of a document
   */
  public async setContent(params: {
    id: string;
    content: string;
  }): Promise<void> {
    console.log('[AbiClient.setContent] doc_id:', params.id, 'content length:', params.content.length);
    const response = await this.execute('set_content', {
      doc_id: params.id,
      content: params.content,
    });
    console.log('[AbiClient.setContent] response:', response);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get the content of a document
   */
  public async getContent(params: { id: string }): Promise<string> {
    const response = await this.execute('get_content', { doc_id: params.id });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get the length of document content
   */
  public async getContentLength(params: { id: string }): Promise<number> {
    const response = await this.execute('get_content_length', { doc_id: params.id });
    if (response.success) {
      return response.result as number;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Add a tag to a document
   */
  public async addTag(params: {
    id: string;
    tag: string;
  }): Promise<void> {
    const response = await this.execute('add_tag', {
      doc_id: params.id,
      tag: params.tag,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Set tags for a document (adds new tags)
   */
  public async setTags(params: {
    id: string;
    tags: string[];
  }): Promise<void> {
    const response = await this.execute('set_tags', {
      doc_id: params.id,
      tags: params.tags,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Update an existing document (convenience method that combines metadata and content updates)
   * This is a high-level method for backwards compatibility
   */
  public async updateDocument(params: {
    id: string;
    title?: string | null;
    content?: string | null;
    tags?: string[] | null;
  }): Promise<void> {
    // Update metadata if title is provided
    if (params.title !== undefined && params.title !== null) {
      await this.updateDocumentMetadata({ id: params.id, title: params.title });
    }

    // Update content if provided
    if (params.content !== undefined && params.content !== null) {
      await this.setContent({ id: params.id, content: params.content });
    }

    // Update tags if provided
    if (params.tags !== undefined && params.tags !== null) {
      await this.setTags({ id: params.id, tags: params.tags });
    }
  }

  /**
   * Delete a document
   */
  public async deleteDocument(params: { id: string }): Promise<void> {
    const response = await this.execute('delete_document', { doc_id: params.id });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Archive or unarchive a document
   */
  public async setArchived(params: {
    id: string;
    archived: boolean;
  }): Promise<void> {
    const response = await this.execute('set_archived', {
      doc_id: params.id,
      archived: params.archived,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get a specific document by ID
   */
  public async getDocument(params: { id: string }): Promise<Document | null> {
    const response = await this.execute('get_document', { doc_id: params.id });
    if (response.success) {
      return response.result as Document | null;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * List all documents (summaries only)
   */
  public async listDocuments(params: {
    include_archived: boolean;
  }): Promise<DocumentSummary[]> {
    const response = await this.execute('list_documents', params);
    if (response.success) {
      return (response.result as DocumentSummary[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Search documents by title or content
   */
  public async searchDocuments(params: {
    query: string;
    include_archived: boolean;
  }): Promise<DocumentSummary[]> {
    const response = await this.execute('search_documents', params);
    if (response.success) {
      return (response.result as DocumentSummary[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get documents by tag
   */
  public async getDocumentsByTag(params: {
    tag: string;
    include_archived: boolean;
  }): Promise<DocumentSummary[]> {
    const response = await this.execute('get_documents_by_tag', params);
    if (response.success) {
      return (response.result as DocumentSummary[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get all unique tags
   */
  public async getAllTags(): Promise<string[]> {
    const response = await this.execute('get_all_tags', {});
    if (response.success) {
      return (response.result as string[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get document statistics
   */
  public async getStats(): Promise<string> {
    const response = await this.execute('get_stats', {});
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get the document count
   */
  public async getDocumentCount(): Promise<number> {
    const response = await this.execute('get_document_count', {});
    if (response.success) {
      return response.result as number;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  // ========== FOLDER METHODS ==========

  /**
   * Create a new folder
   */
  public async createFolder(params: {
    name: string;
    parent_id?: string | null;
    color?: string | null;
  }): Promise<string> {
    const response = await this.execute('create_folder', {
      name: params.name,
      parent_id: params.parent_id ?? null,
      color: params.color ?? null,
    });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Rename a folder
   */
  public async renameFolder(params: {
    folder_id: string;
    name: string;
  }): Promise<void> {
    const response = await this.execute('rename_folder', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Set folder color
   */
  public async setFolderColor(params: {
    folder_id: string;
    color: string | null;
  }): Promise<void> {
    const response = await this.execute('set_folder_color', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Move a folder to a new parent
   */
  public async moveFolder(params: {
    folder_id: string;
    new_parent_id: string | null;
  }): Promise<void> {
    const response = await this.execute('move_folder', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Delete a folder
   */
  public async deleteFolder(params: {
    folder_id: string;
    recursive?: boolean;
  }): Promise<void> {
    const response = await this.execute('delete_folder', {
      folder_id: params.folder_id,
      recursive: params.recursive ?? false,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get a folder by ID
   */
  public async getFolder(params: { folder_id: string }): Promise<FolderResponse | null> {
    const response = await this.execute('get_folder', params);
    if (response.success) {
      return response.result as FolderResponse | null;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * List all folders
   */
  public async listFolders(): Promise<FolderResponse[]> {
    const response = await this.execute('list_folders', {});
    if (response.success) {
      return (response.result as FolderResponse[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get folder tree structure
   */
  public async getFolderTree(): Promise<FolderTreeItem[]> {
    const response = await this.execute('get_folder_tree', {});
    if (response.success) {
      return (response.result as FolderTreeItem[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get documents in a specific folder
   */
  public async getDocumentsInFolder(params: {
    folder_id: string | null;
    include_archived: boolean;
  }): Promise<DocumentSummary[]> {
    const response = await this.execute('get_documents_in_folder', params);
    if (response.success) {
      return (response.result as DocumentSummary[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Move a document to a different folder
   */
  public async moveDocument(params: {
    doc_id: string;
    folder_id: string | null;
  }): Promise<void> {
    const response = await this.execute('move_document', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get folder count
   */
  public async getFolderCount(): Promise<number> {
    const response = await this.execute('get_folder_count', {});
    if (response.success) {
      return response.result as number;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  // ========== CONTEXT GROUP METHODS ==========

  /**
   * Set the human-readable name for this context
   */
  public async setContextName(params: { name: string }): Promise<void> {
    const response = await this.execute('set_context_name', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get the human-readable name for this context
   */
  public async getContextName(): Promise<string> {
    const response = await this.execute('get_context_name', {});
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Register a folder context in the General context's registry
   */
  public async registerFolder(params: {
    context_id: string;
    name: string;
    color?: string | null;
  }): Promise<void> {
    const response = await this.execute('register_folder', {
      context_id: params.context_id,
      name: params.name,
      color: params.color ?? null,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Update the registered name of a folder context in the General registry
   */
  public async updateFolderName(params: {
    context_id: string;
    name: string;
  }): Promise<void> {
    const response = await this.execute('update_folder_name', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Remove a folder context from the General context's registry
   */
  public async unregisterFolder(params: { context_id: string }): Promise<void> {
    const response = await this.execute('unregister_folder', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * Get all folder contexts registered in the General context
   */
  public async getFolderRegistry(): Promise<FolderRegistryEntry[]> {
    const response = await this.execute('get_folder_registry', {});
    if (response.success) {
      return (response.result as FolderRegistryEntry[]) || [];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }
}
