/**
 * Landing content for Merraria.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { CloudX, Cube3DStacked, Monitor, Wifi, WifiOff } from '@calimero-network/mero-icons';

import Animation from './animation';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Merraria",
  packageId: "com.calimero.merraria",
  tagline: "Terraria-style P2P mining sandbox. The world is a Calimero context: seed + tile-edit diff + player presence, no game server.",
  dir: "merraria",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  playableOffline: true,
  trust: ["No game server", "Deterministic world", "Plays offline"],
  explainer: [
    "A Terraria-style mining and building sandbox, seen from the side, shared with other players and hosted by nobody. Like Mero Blocks, the world is a Calimero context: a seed, the diff of every tile anyone has changed, and player presence.",
    "The terrain generator is deterministic, so the seed plus the edits reproduce the same world everywhere and only the edits have to travel. It also runs with no node at all if you want to dig alone.",
  ],
  features: [
    {
      icon: CloudX,
      title: "No game server",
      body: "The world is a seed plus a tile-edit diff, in a context you own. Nothing to host.",
    },
    {
      icon: WifiOff,
      title: "Plays fully offline",
      body: "No node needed. The world persists locally and is yours until you invite anyone.",
    },
    {
      icon: Cube3DStacked,
      title: "Deterministic terrain",
      body: "The same seed builds the same world on every peer, so only your changes replicate.",
    },
    {
      icon: Wifi,
      title: "See other players",
      body: "Presence rides alongside the tile edits, so you watch people mine in real time.",
    },
    {
      icon: Monitor,
      title: "Runs in a browser",
      body: "A Canvas2D renderer over a pure-TypeScript engine. Nothing to install.",
    },
  ],
  animation: Animation,
};
