/**
 * Landing content for Battleships.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { ArrowUpRight, ExternalLink, EyeOff, LockCheck, Target } from '@calimero-network/mero-icons';

import Animation from './animation';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Battleships",
  packageId: "com.calimero.battleships",
  tagline: "Two-player Battleships over Calimero: a lobby service for matchmaking and a game service per match, with commit-reveal ship placement.",
  dir: "battleships",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Boards never leave your node", "Commit-reveal placement", "No accounts"],
  explainer: [
    "Turn-based Battleships for two players, where the interesting part is not the game — it is the trust model. Your fleet lives in private, node-local storage, so your opponent’s node never holds a copy of it at any point.",
    "Placement is commit-reveal: you commit to a board up front and reveal it at the end, so neither side can quietly move a ship after seeing where the shots are going. A lobby service handles matchmaking and a separate game service runs each match.",
  ],
  features: [
    {
      icon: EyeOff,
      title: "A board your opponent cannot read",
      body: "Ships live in `#[app::private]` storage that never replicates. There is no copy on their node to inspect.",
    },
    {
      icon: LockCheck,
      title: "Commit-reveal placement",
      body: "You commit to a fleet before play and reveal it after. Neither player can change their board mid-game.",
    },
    {
      icon: Target,
      title: "Matchmaking without a server",
      body: "A lobby service pairs players and a game service runs each match, both inside the same bundle.",
    },
    {
      icon: ArrowUpRight,
      title: "Results reported back",
      body: "A finished match tells the lobby who won through a cross-context call, so history survives the game.",
    },
    {
      icon: ExternalLink,
      title: "Invite by link",
      body: "Recursive namespace invitations. No sign-up, no account, no email address.",
    },
  ],
  animation: Animation,
};
