/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface AxisData {
  pos: string;
  deleted: boolean;
  updated_at: number;
}

export interface AxisEntryView {
  id: string;
  pos: string;
  deleted: boolean;
}

export type AxisOpPayload =
  | { name: 'InsertRow'; payload: AxisOp_InsertRow }
  | { name: 'InsertCol'; payload: AxisOp_InsertCol }
  | { name: 'DeleteRow'; payload: AxisOp_DeleteRow }
  | { name: 'DeleteCol'; payload: AxisOp_DeleteCol }
  | { name: 'RestoreRow'; payload: AxisOp_RestoreRow }
  | { name: 'RestoreCol'; payload: AxisOp_RestoreCol }

export const AxisOp = {
  InsertRow: (insertrow: AxisOp_InsertRow): AxisOpPayload => ({ name: 'InsertRow', payload: insertrow }),
  InsertCol: (insertcol: AxisOp_InsertCol): AxisOpPayload => ({ name: 'InsertCol', payload: insertcol }),
  DeleteRow: (deleterow: AxisOp_DeleteRow): AxisOpPayload => ({ name: 'DeleteRow', payload: deleterow }),
  DeleteCol: (deletecol: AxisOp_DeleteCol): AxisOpPayload => ({ name: 'DeleteCol', payload: deletecol }),
  RestoreRow: (restorerow: AxisOp_RestoreRow): AxisOpPayload => ({ name: 'RestoreRow', payload: restorerow }),
  RestoreCol: (restorecol: AxisOp_RestoreCol): AxisOpPayload => ({ name: 'RestoreCol', payload: restorecol }),
} as const;

export interface AxisOp_DeleteCol {
  id: string;
}

export interface AxisOp_DeleteRow {
  id: string;
}

export interface AxisOp_InsertCol {
  id: string;
  pos: string;
}

export interface AxisOp_InsertRow {
  id: string;
  pos: string;
}

export interface AxisOp_RestoreCol {
  id: string;
}

export interface AxisOp_RestoreRow {
  id: string;
}

export interface Cell {
  id: string;
  sheet_id: string;
  row_id: string;
  col_id: string;
  raw_value: string;
  computed_value: string;
  format: string;
  updated_at: number;
}

export interface CellData {
  id: string;
  sheet_id: string;
  row: number;
  col: number;
  raw_value: string;
  format: string;
  updated_at: number;
}

export type CellOpPayload =
  | { name: 'Set'; payload: CellOp_Set }
  | { name: 'Format'; payload: CellOp_Format }
  | { name: 'Clear'; payload: CellOp_Clear }

export const CellOp = {
  Set: (set: CellOp_Set): CellOpPayload => ({ name: 'Set', payload: set }),
  Format: (format: CellOp_Format): CellOpPayload => ({ name: 'Format', payload: format }),
  Clear: (clear: CellOp_Clear): CellOpPayload => ({ name: 'Clear', payload: clear }),
} as const;

export interface CellOp_Clear {
  row_id: string;
  col_id: string;
}

export interface CellOp_Format {
  row_id: string;
  col_id: string;
  format: string;
}

export interface CellOp_Set {
  row_id: string;
  col_id: string;
  raw_value: string;
}

export interface Event_AxesChanged {
  sheet_id: string;
  count: number;
}

export interface Event_CellCleared {
  sheet_id: string;
  row_id: string;
  col_id: string;
}

export interface Event_CellUpdated {
  id: string;
  sheet_id: string;
}

export interface Event_CellsChanged {
  sheet_id: string;
  count: number;
}

export interface Event_MemberJoined {
  id: string;
  nickname: string;
}

export interface Event_MemberRenamed {
  id: string;
  nickname: string;
}

export interface Event_Migrated {
  from_version: string;
  to_version: string;
}

export interface Event_NamedRangesChanged {
  name: string;
}

export interface Event_ProjectInitialized {
  id: string;
  name: string;
}

export interface Event_SheetCreated {
  id: string;
  name: string;
}

export interface Event_SheetDeleted {
  id: string;
}

export interface Event_SheetRenamed {
  id: string;
  name: string;
}

export interface FormatData {
  format: string;
  updated_at: number;
}

export interface FunctionDef {
  name: string;
  category: string;
  syntax: string;
  description: string;
  example: string;
}

export interface Member {
  id: string;
  nickname: string;
  joined_at: number;
  updated_at: number;
}

export interface MemberData {
  nickname: string;
  joined_at: number;
  updated_at: number;
}

export interface NamedRange {
  name: string;
  target: string;
}

export interface NamedRangeData {
  name: string;
  target: string;
  updated_at: number;
}

export interface Project {
  id: string;
  name: string;
  created_at: number;
}

export interface Sheet {
  id: string;
  name: string;
  position: number;
  created_at: number;
}

export interface SheetData {
  id: string;
  name: string;
  position: number;
  created_at: number;
  updated_at: number;
}

export interface SheetLayout {
  sheet_id: string;
  rows: AxisEntryView[];
  cols: AxisEntryView[];
}

export interface Spreadsheet {
  project_id: string;
  project_name: string;
  project_created_at: number;
  sheets: Record<string, SheetData>;
  cells: Record<string, CellData>;
  members: Record<string, MemberData>;
  axes: Record<string, AxisData>;
  formats: Record<string, FormatData>;
  names: Record<string, NamedRangeData>;
}













export type AbiEvent =
  | { name: "AxesChanged"; payload: Event_AxesChanged }
  | { name: "CellCleared"; payload: Event_CellCleared }
  | { name: "CellUpdated"; payload: Event_CellUpdated }
  | { name: "CellsChanged"; payload: Event_CellsChanged }
  | { name: "MemberJoined"; payload: Event_MemberJoined }
  | { name: "MemberRenamed"; payload: Event_MemberRenamed }
  | { name: "Migrated"; payload: Event_Migrated }
  | { name: "NamedRangesChanged"; payload: Event_NamedRangesChanged }
  | { name: "ProjectInitialized"; payload: Event_ProjectInitialized }
  | { name: "SheetCreated"; payload: Event_SheetCreated }
  | { name: "SheetDeleted"; payload: Event_SheetDeleted }
  | { name: "SheetRenamed"; payload: Event_SheetRenamed }
;


export class SpreadsheetClient {
  private _mero: MeroJs;
  private _contextId: string;

  constructor(mero: MeroJs, contextId: string) {
    this._mero = mero;
    this._contextId = contextId;
  }

  /**
   * apply_axis_ops
   *
   * @intent mutating
   */
  public async applyAxisOps(params: { sheet_id: string; ops: AxisOpPayload[] }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'apply_axis_ops', argsJson: params });
    return response as void;
  }

  /**
   * apply_cell_ops
   *
   * @intent mutating
   */
  public async applyCellOps(params: { sheet_id: string; ops: CellOpPayload[] }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'apply_cell_ops', argsJson: params });
    return response as void;
  }

  /**
   * clear_cell
   *
   * @intent mutating
   */
  public async clearCell(params: { sheet_id: string; row_id: string; col_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'clear_cell', argsJson: params });
    return response as void;
  }

  /**
   * create_sheet
   *
   * @intent mutating
   */
  public async createSheet(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_sheet', argsJson: params });
    return response as string;
  }

  /**
   * delete_named_range
   *
   * @intent mutating
   */
  public async deleteNamedRange(params: { name: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_named_range', argsJson: params });
    return response as void;
  }

  /**
   * delete_sheet
   *
   * @intent mutating
   */
  public async deleteSheet(params: { sheet_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_sheet', argsJson: params });
    return response as void;
  }

  /**
   * export_all
   *
   * @intent read_only
   */
  public async exportAll(): Promise<Sheet[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'export_all', argsJson: {} });
    return response as Sheet[];
  }

  /**
   * get_all_cells
   *
   * @intent read_only
   */
  public async getAllCells(): Promise<Cell[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_all_cells', argsJson: {} });
    return response as Cell[];
  }

  /**
   * get_cells
   *
   * @intent read_only
   */
  public async getCells(params: { sheet_id: string }): Promise<Cell[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_cells', argsJson: params });
    return response as Cell[];
  }

  /**
   * get_functions
   *
   * @intent read_only
   */
  public async getFunctions(): Promise<FunctionDef[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_functions', argsJson: {} });
    return response as FunctionDef[];
  }

  /**
   * get_layouts
   *
   * @intent read_only
   */
  public async getLayouts(): Promise<SheetLayout[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_layouts', argsJson: {} });
    return response as SheetLayout[];
  }

  /**
   * get_members
   *
   * @intent read_only
   */
  public async getMembers(): Promise<Member[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_members', argsJson: {} });
    return response as Member[];
  }

  /**
   * get_named_ranges
   *
   * @intent read_only
   */
  public async getNamedRanges(): Promise<NamedRange[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_named_ranges', argsJson: {} });
    return response as NamedRange[];
  }

  /**
   * get_project
   *
   * @intent read_only
   */
  public async getProject(): Promise<Project> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_project', argsJson: {} });
    return response as Project;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {} });
    return response as void;
  }

  /**
   * init_project
   *
   * @intent mutating
   */
  public async initProject(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init_project', argsJson: params });
    return response as string;
  }

  /**
   * join
   *
   * @intent mutating
   */
  public async join(params: { nickname: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'join', argsJson: params });
    return response as void;
  }

  /**
   * list_sheets
   *
   * @intent read_only
   */
  public async listSheets(): Promise<Sheet[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_sheets', argsJson: {} });
    return response as Sheet[];
  }

  /**
   * rename_sheet
   *
   * @intent mutating
   */
  public async renameSheet(params: { sheet_id: string; new_name: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'rename_sheet', argsJson: params });
    return response as void;
  }

  /**
   * search_functions
   *
   * @intent read_only
   */
  public async searchFunctions(params: { prefix: string }): Promise<FunctionDef[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'search_functions', argsJson: params });
    return response as FunctionDef[];
  }

  /**
   * set_cell
   *
   * @intent mutating
   */
  public async setCell(params: { sheet_id: string; row_id: string; col_id: string; raw_value: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_cell', argsJson: params });
    return response as string;
  }

  /**
   * set_cell_format
   *
   * @intent mutating
   */
  public async setCellFormat(params: { sheet_id: string; row_id: string; col_id: string; format: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_cell_format', argsJson: params });
    return response as string;
  }

  /**
   * set_named_range
   *
   * @intent mutating
   */
  public async setNamedRange(params: { name: string; target: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_named_range', argsJson: params });
    return response as void;
  }

  /**
   * whoami
   *
   * @intent read_only
   */
  public async whoami(): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'whoami', argsJson: {} });
    return response as string;
  }

}