/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Cell {
  id: string;
  sheet_id: string;
  row: number;
  col: number;
  raw_value: string;
  computed_value: string;
  format: string;
  updated_at: number;
}

export interface CellData {
  id: string;
  sheet_id: string;
  row: number;
  col: number;
  raw_value: string;
  format: string;
  updated_at: number;
}

export type CellOpPayload =
  | { name: 'Set'; payload: CellOp_Set }
  | { name: 'Format'; payload: CellOp_Format }
  | { name: 'Clear'; payload: CellOp_Clear }

export const CellOp = {
  Set: (set: CellOp_Set): CellOpPayload => ({ name: 'Set', payload: set }),
  Format: (format: CellOp_Format): CellOpPayload => ({ name: 'Format', payload: format }),
  Clear: (clear: CellOp_Clear): CellOpPayload => ({ name: 'Clear', payload: clear }),
} as const;

export interface CellOp_Clear {
  row: number;
  col: number;
}

export interface CellOp_Format {
  row: number;
  col: number;
  format: string;
}

export interface CellOp_Set {
  row: number;
  col: number;
  raw_value: string;
}

export interface Cursor {
  id: string;
  author: string;
  sheet_id: string;
  row: number;
  col: number;
  color: string;
  updated_at: number;
}

export interface CursorData {
  sheet_id: string;
  row: number;
  col: number;
  color: string;
  updated_at: number;
}

export interface Event_CellCleared {
  sheet_id: string;
  row: number;
  col: number;
}

export interface Event_CellUpdated {
  id: string;
  sheet_id: string;
}

export interface Event_CellsChanged {
  sheet_id: string;
  count: number;
}

export interface Event_CursorMoved {
  author: string;
  sheet_id: string;
}

export interface Event_CursorRemoved {
  author: string;
}

export interface Event_MemberJoined {
  id: string;
  nickname: string;
}

export interface Event_MemberRenamed {
  id: string;
  nickname: string;
}

export interface Event_ProjectInitialized {
  id: string;
  name: string;
}

export interface Event_SheetCreated {
  id: string;
  name: string;
}

export interface Event_SheetDeleted {
  id: string;
}

export interface Event_SheetRenamed {
  id: string;
  name: string;
}

export interface FunctionDef {
  name: string;
  syntax: string;
  description: string;
  example: string;
}

export interface Member {
  id: string;
  nickname: string;
  joined_at: number;
  updated_at: number;
}

export interface MemberData {
  nickname: string;
  joined_at: number;
  updated_at: number;
}

export interface Project {
  id: string;
  name: string;
  created_at: number;
}

export interface Sheet {
  id: string;
  name: string;
  position: number;
  created_at: number;
}

export interface SheetData {
  id: string;
  name: string;
  position: number;
  created_at: number;
  updated_at: number;
}

export interface Spreadsheet {
  project_id: string;
  project_name: string;
  project_created_at: number;
  sheets: Record<string, SheetData>;
  cells: Record<string, CellData>;
  cursors: Record<string, CursorData>;
  members: Record<string, MemberData>;
}












export type AbiEvent =
  | { name: "CellCleared"; payload: Event_CellCleared }
  | { name: "CellUpdated"; payload: Event_CellUpdated }
  | { name: "CellsChanged"; payload: Event_CellsChanged }
  | { name: "CursorMoved"; payload: Event_CursorMoved }
  | { name: "CursorRemoved"; payload: Event_CursorRemoved }
  | { name: "MemberJoined"; payload: Event_MemberJoined }
  | { name: "MemberRenamed"; payload: Event_MemberRenamed }
  | { name: "ProjectInitialized"; payload: Event_ProjectInitialized }
  | { name: "SheetCreated"; payload: Event_SheetCreated }
  | { name: "SheetDeleted"; payload: Event_SheetDeleted }
  | { name: "SheetRenamed"; payload: Event_SheetRenamed }
;


export class SpreadsheetClient {
  private _mero: MeroJs;
  private _contextId: string;

  constructor(mero: MeroJs, contextId: string) {
    this._mero = mero;
    this._contextId = contextId;
  }

  /**
   * apply_cell_ops
   *
   * @intent mutating
   */
  public async applyCellOps(params: { sheet_id: string; ops: CellOpPayload[] }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'apply_cell_ops', argsJson: params });
    return response as void;
  }

  /**
   * clear_cell
   *
   * @intent mutating
   */
  public async clearCell(params: { sheet_id: string; row: number; col: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'clear_cell', argsJson: params });
    return response as void;
  }

  /**
   * create_sheet
   *
   * @intent mutating
   */
  public async createSheet(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_sheet', argsJson: params });
    return response as string;
  }

  /**
   * delete_sheet
   *
   * @intent mutating
   */
  public async deleteSheet(params: { sheet_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_sheet', argsJson: params });
    return response as void;
  }

  /**
   * export_all
   *
   * @intent read_only
   */
  public async exportAll(): Promise<Sheet[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'export_all', argsJson: {} });
    return response as Sheet[];
  }

  /**
   * get_all_cells
   *
   * @intent read_only
   */
  public async getAllCells(): Promise<Cell[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_all_cells', argsJson: {} });
    return response as Cell[];
  }

  /**
   * get_cells
   *
   * @intent read_only
   */
  public async getCells(params: { sheet_id: string }): Promise<Cell[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_cells', argsJson: params });
    return response as Cell[];
  }

  /**
   * get_cursors
   *
   * @intent read_only
   */
  public async getCursors(): Promise<Cursor[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_cursors', argsJson: {} });
    return response as Cursor[];
  }

  /**
   * get_functions
   *
   * @intent read_only
   */
  public async getFunctions(): Promise<FunctionDef[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_functions', argsJson: {} });
    return response as FunctionDef[];
  }

  /**
   * get_members
   *
   * @intent read_only
   */
  public async getMembers(): Promise<Member[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_members', argsJson: {} });
    return response as Member[];
  }

  /**
   * get_project
   *
   * @intent read_only
   */
  public async getProject(): Promise<Project> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_project', argsJson: {} });
    return response as Project;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {} });
    return response as void;
  }

  /**
   * init_project
   *
   * @intent mutating
   */
  public async initProject(params: { name: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init_project', argsJson: params });
    return response as string;
  }

  /**
   * join
   *
   * @intent mutating
   */
  public async join(params: { nickname: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'join', argsJson: params });
    return response as void;
  }

  /**
   * list_sheets
   *
   * @intent read_only
   */
  public async listSheets(): Promise<Sheet[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_sheets', argsJson: {} });
    return response as Sheet[];
  }

  /**
   * remove_cursor
   *
   * @intent mutating
   */
  public async removeCursor(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'remove_cursor', argsJson: {} });
    return response as void;
  }

  /**
   * rename_sheet
   *
   * @intent mutating
   */
  public async renameSheet(params: { sheet_id: string; new_name: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'rename_sheet', argsJson: params });
    return response as void;
  }

  /**
   * search_functions
   *
   * @intent read_only
   */
  public async searchFunctions(params: { prefix: string }): Promise<FunctionDef[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'search_functions', argsJson: params });
    return response as FunctionDef[];
  }

  /**
   * set_cell
   *
   * @intent mutating
   */
  public async setCell(params: { sheet_id: string; row: number; col: number; raw_value: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_cell', argsJson: params });
    return response as string;
  }

  /**
   * set_cell_format
   *
   * @intent mutating
   */
  public async setCellFormat(params: { sheet_id: string; row: number; col: number; format: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_cell_format', argsJson: params });
    return response as string;
  }

  /**
   * set_cell_formula
   *
   * @intent mutating
   */
  public async setCellFormula(params: { sheet_id: string; row: number; col: number; formula: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_cell_formula', argsJson: params });
    return response as string;
  }

  /**
   * update_cursor
   *
   * @intent mutating
   */
  public async updateCursor(params: { sheet_id: string; row: number; col: number }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'update_cursor', argsJson: params });
    return response as void;
  }

  /**
   * whoami
   *
   * @intent read_only
   */
  public async whoami(): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'whoami', argsJson: {} });
    return response as string;
  }

}