/**
 * Landing content for Mero Pass.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { Clock, CloudX, LockBox, LockStar, ShieldCheck } from '@calimero-network/mero-icons';

import Animation from './animation';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Pass",
  packageId: "com.calimero.mero-pass",
  tagline: "A peer-to-peer secret manager: keep credentials in a vault on your own nodes and share them with namespace members.",
  dir: "mero-pass",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Vault on your nodes", "Five secret types", "No vendor to breach"],
  explainer: [
    "A secret manager for a team, where the vault sits on your own nodes rather than in a company whose breach notification you will read about later. You create a vault, invite the people who need it, and the contents replicate only between their nodes and yours.",
    "It handles the five things teams actually share: logins, notes, one-time-password seeds, SSH keys, and free-form secrets — with roles, so not everyone who can read a vault can change who else does.",
  ],
  features: [
    {
      icon: LockBox,
      title: "Vaults with roles",
      body: "Owner, admin and member. Reading a vault and controlling its membership are different powers.",
    },
    {
      icon: LockStar,
      title: "Five secret types",
      body: "Logins with URLs, secure notes, TOTP seeds, SSH keypairs, and free-form entries.",
    },
    {
      icon: Clock,
      title: "TOTP codes",
      body: "Time-based one-time passwords generated locally from a seed that never leaves your nodes.",
    },
    {
      icon: ShieldCheck,
      title: "Share with members",
      body: "Scoped to the people you invited. Revoking access is something you do, not request.",
    },
    {
      icon: CloudX,
      title: "No vendor to breach",
      body: "There is no central vault to attack, because there is no central vault.",
    },
  ],
  animation: Animation,
};
