// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, cell, enterCell, withTwoMembers } from './helpers';

test.describe(`collaborator: add, rename, or delete sheet tabs within the project`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a collaborator adds a new sheet, every participant sees the new tab appear in the tab bar within 3s`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await expect(b.getByTestId('item-sheet')).toHaveCount(1);
      await a.getByTestId('action-create_sheet').click();
      await expect(a.getByTestId('item-sheet')).toHaveCount(2);
      await expect(b.getByTestId('item-sheet')).toHaveCount(2, { timeout: 60_000 });
    });
  });

  test(`after a sheet is renamed, the updated name shows for everyone within 3s`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await a.getByTestId('item-sheet').first().dblclick();
      const input = a.getByLabel('Rename sheet');
      await input.fill('Budget 2026');
      await input.press('Enter');
      await expect(a.getByTestId('item-sheet').first()).toContainText('Budget 2026');
      await expect(b.getByTestId('item-sheet').first()).toContainText('Budget 2026', { timeout: 60_000 });
    });
  });

  test(`after a sheet is deleted, the tab and all its cell data disappear for everyone`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await a.getByTestId('action-create_sheet').click();
      const tabsA = a.getByTestId('item-sheet');
      const tabsB = b.getByTestId('item-sheet');
      await expect(tabsA).toHaveCount(2);
      await tabsA.nth(1).click();
      await enterCell(a, 0, 0, 'doomed');
      await expect(tabsB).toHaveCount(2, { timeout: 60_000 });
      await tabsB.nth(1).click();
      await expect(cell(b, 0, 0)).toHaveText('doomed', { timeout: 60_000 });
      const doomed = (await tabsA.nth(1).getAttribute('data-sheet-id'))!;

      await tabsA.nth(1).getByTestId('action-delete_sheet').click();
      await expect(tabsA).toHaveCount(1);
      await expect(tabsB).toHaveCount(1, { timeout: 60_000 });
      await expect(b.locator(`[data-testid="item-sheet"][data-sheet-id="${doomed}"]`)).toHaveCount(0);
      // Bob was looking at it: he lands on the remaining sheet, without its cells.
      await expect(b.getByTestId('item-cell').filter({ hasText: 'doomed' })).toHaveCount(0);
    });
  });
});
