// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, cell, openNewWorkbook, shareWorkbook } from './helpers';

test.describe(`project owner: create a new spreadsheet project and invite collaborators`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after the owner names the project and confirms, every invited collaborator sees the spreadsheet with a default blank sheet within 5s`, async ({ browser }) => {
    const ctxA = await browser.newContext();
    const ctxB = await browser.newContext();
    try {
      const a = await ctxA.newPage();
      const b = await ctxB.newPage();
      await openNewWorkbook(a, { name: 'Team plan', nickname: 'Alice' });
      await expect(a.getByTestId('item-sheet')).toHaveCount(1);
      await shareWorkbook(a, b, { nickname: 'Bob' });

      await expect(b.getByText('Team plan').first()).toBeVisible();
      await expect(b.getByTestId('item-sheet')).toHaveCount(1);
      await expect(b.getByTestId('item-sheet').first()).toHaveText(await a.getByTestId('item-sheet').first().innerText());
      // Blank: no cell holds anything.
      await expect(cell(b, 0, 0)).toHaveText('');
      await expect(b.getByTestId('item-cell').filter({ hasText: /\S/ })).toHaveCount(0);
      // And the owner sees them arrive.
      await expect(a.getByTestId('collaborator-avatar')).toHaveCount(2, { timeout: 60_000 });
    } finally {
      await ctxA.close();
      await ctxB.close();
    }
  });
});
