// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { readFileSync } from 'fs';
import { loginViaHash, clearAuth, cell, enterCell, openNewWorkbook } from './helpers';

test.describe(`anyone in the project: download the current spreadsheet as a file`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`clicking download produces a CSV file containing all sheets' data with sheet names as separators`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Export me' });
    await enterCell(page, 0, 0, 'Item');
    await enterCell(page, 0, 1, 'Cost');
    await enterCell(page, 1, 0, 'Rent');
    await enterCell(page, 1, 1, '1200');

    await page.getByTestId('action-create_sheet').click();
    await expect(page.getByTestId('item-sheet')).toHaveCount(2);
    await page.getByTestId('item-sheet').nth(1).click();
    await enterCell(page, 0, 0, 'second');

    const [download] = await Promise.all([page.waitForEvent('download'), page.getByTestId('action-export_all').click()]);
    expect(download.suggestedFilename()).toBe('export-me.csv');
    const csv = readFileSync((await download.path())!, 'utf-8');
    const sheetNames = await page.getByTestId('item-sheet').allInnerTexts();
    expect(csv).toBe([
      `# ${sheetNames[0].replace('×', '').trim()}`, '"Item","Cost"', '"Rent","1200"', '',
      `# ${sheetNames[1].replace('×', '').trim()}`, '"second"', '',
    ].join('\n'));
  });

  test(`the downloaded file reflects the latest state of every cell at the moment of export`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Latest' });
    await enterCell(page, 0, 0, '1');
    await enterCell(page, 0, 1, '=A1+1');
    const download = async () => {
      const [d] = await Promise.all([page.waitForEvent('download'), page.getByTestId('action-export_all').click()]);
      return readFileSync((await d.path())!, 'utf-8');
    };
    expect(await download()).toContain('"1","2"');
    await enterCell(page, 0, 0, '41');
    await expect(cell(page, 0, 1)).toHaveText('42');
    const csv = await download();
    expect(csv).toContain('"41","42"');
    expect(csv).not.toContain('"1","2"');
  });
});
