// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, cell, enterCell, openNewWorkbook } from './helpers';

test.describe(`anyone in the project: open a help section that lists every available function with its syntax and a short example`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`the help panel lists every supported function alphabetically with its name, syntax pattern, and at least one usage example`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Help' });
    await page.getByLabel('Open function reference').click();
    const panel = page.getByRole('dialog', { name: 'Function reference' });
    await expect(panel).toBeVisible();
    const cards = panel.locator('li');
    const count = await cards.count();
    expect(count).toBeGreaterThan(20);
    await expect(panel.getByText(`${count} functions`)).toBeVisible();

    const names = await cards.evaluateAll((els) => els.map((el) => el.firstElementChild?.firstChild?.textContent ?? ''));
    expect(names).toEqual([...names].sort((x, y) => x.localeCompare(y)));
    for (const n of ['SUM', 'AVERAGE', 'MIN', 'MAX', 'COUNT', 'IF']) expect(names).toContain(n);

    const sum = cards.filter({ has: page.getByText(/^SUM\(/) }).first();
    await expect(sum).toContainText('Example');
    await expect(sum.locator('code')).toContainText('=SUM(');
  });

  test(`the help panel includes a search box that filters the function list as the user types`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Help' });
    await page.getByLabel('Open function reference').click();
    const panel = page.getByRole('dialog', { name: 'Function reference' });
    const total = await panel.locator('li').count();
    await panel.getByLabel('Search functions').fill('aver');
    await expect.poll(() => panel.locator('li').count()).toBeLessThan(total);
    await expect(panel.locator('li').first()).toContainText('AVERAGE');
    await panel.getByLabel('Search functions').fill('nosuchfunction');
    await expect(panel.getByText('No functions match "nosuchfunction"')).toBeVisible();
    await panel.getByLabel('Clear search').click();
    await expect(panel.locator('li')).toHaveCount(total);
  });

  test(`the help panel can be opened and closed without losing the current spreadsheet state`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Help' });
    await enterCell(page, 0, 0, '7');
    await enterCell(page, 0, 1, '=A1*6');
    await expect(cell(page, 0, 1)).toHaveText('42');
    await cell(page, 0, 1).click();

    await page.getByLabel('Open function reference').click();
    const panel = page.getByRole('dialog', { name: 'Function reference' });
    await expect(panel).toBeVisible();
    await panel.getByRole('button', { name: 'Close function help' }).click();
    await expect(panel).toBeHidden();

    await expect(cell(page, 0, 0)).toHaveText('7');
    await expect(cell(page, 0, 1)).toHaveText('42');
    await expect(page.getByLabel('Formula bar')).toHaveValue('=A1*6');
  });
});
