// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, cell, openNewWorkbook } from './helpers';

test.describe(`collaborator: see matching functions suggested as I start typing a formula`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after typing '=' followed by one or more letters, a dropdown appears listing all functions whose names start with those letters`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Suggestions' });
    await cell(page, 0, 0).click();
    await page.keyboard.type('=SU');
    const options = page.getByRole('listbox', { name: 'Function suggestions' }).getByRole('option');
    await expect(options.first()).toBeVisible();
    const names = await options.locator('.fn-name').allInnerTexts();
    expect(names).toContain('SUM');
    for (const n of names) expect(n.startsWith('SU')).toBe(true);
  });

  test(`selecting a suggestion from the dropdown inserts the function name and opening parenthesis into the cell`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Suggestions' });
    await cell(page, 0, 0).click();
    await page.keyboard.type('=AVER');
    await page.getByRole('option').filter({ has: page.locator('.fn-name', { hasText: /^AVERAGE$/ }) }).click();
    const bar = page.getByLabel('Formula bar');
    await expect(bar).toHaveValue('=AVERAGE(');
    await expect(page.getByRole('listbox', { name: 'Function suggestions' })).toBeHidden();

    // And the formula can be finished and committed from there.
    await page.keyboard.type('4,8)');
    await page.keyboard.press('Enter');
    await expect(cell(page, 0, 0)).toHaveText('6');
  });

  test(`the dropdown disappears when the user clears the formula bar or presses Escape`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Suggestions' });
    const list = page.getByRole('listbox', { name: 'Function suggestions' });
    await cell(page, 0, 0).click();
    await page.keyboard.type('=MA');
    await expect(list).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(list).toBeHidden();

    await cell(page, 1, 0).click();
    await page.keyboard.type('=MI');
    await expect(list).toBeVisible();
    await page.getByLabel('Formula bar').fill('');
    await expect(list).toBeHidden();
  });
});
