// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import { loginViaHash, clearAuth, cell, withTwoMembers } from './helpers';

test.describe(`collaborator: see each person's selected cell highlighted in their unique color`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  // A peer's cursor draws a solid outline in their colour on the cell.
  const outline = (page: Page, row: number, col: number) =>
    cell(page, row, col).evaluate((el) => {
      const s = getComputedStyle(el);
      return s.outlineStyle === 'solid' ? s.outlineColor : null;
    });
  const avatarColors = (page: Page) => page.getByTestId('collaborator-avatar')
    .evaluateAll((els) => els.map((el) => getComputedStyle(el).backgroundColor));

  test(`when a collaborator selects a cell, every other collaborator sees that cell highlighted in that person's assigned color within 1s`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await cell(a, 3, 2).click();
      await expect.poll(() => outline(b, 3, 2), { timeout: 60_000 }).not.toBeNull();
      // Alice's colour on Bob's screen is the one Bob's roster gives her.
      const alice = b.locator('[data-testid="collaborator-avatar"][title="Alice"]');
      const aliceColor = await alice.evaluate((el) => getComputedStyle(el).backgroundColor);
      expect(await outline(b, 3, 2)).toBe(aliceColor);

      // She moves; the highlight follows promptly.
      const started = Date.now();
      await cell(a, 5, 4).click();
      await expect.poll(() => outline(b, 5, 4), { timeout: 10_000 }).not.toBeNull();
      console.log(`cursor move arrived in ${Date.now() - started}ms`);
      expect(await outline(b, 3, 2)).toBeNull();
    });
  });

  test(`each connected user is assigned a distinct color that persists for the duration of their session`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await expect(a.getByTestId('collaborator-avatar')).toHaveCount(2, { timeout: 60_000 });
      await expect(b.getByTestId('collaborator-avatar')).toHaveCount(2, { timeout: 60_000 });
      const first = await avatarColors(a);
      expect(new Set(first).size).toBe(2);

      await cell(a, 1, 1).click();
      await cell(b, 2, 2).click();
      await cell(a, 4, 4).click();
      expect(await avatarColors(a)).toEqual(first);
    });
  });

  test(`when a user disconnects, their cursor highlight disappears for everyone`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await cell(b, 6, 1).click();
      await expect.poll(() => outline(a, 6, 1), { timeout: 60_000 }).not.toBeNull();
      await b.close();
      await expect.poll(() => outline(a, 6, 1), { timeout: 30_000 }).toBeNull();
    });
  });
});
