// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, cell, enterCell, withTwoMembers } from './helpers';

test.describe(`collaborator: type values or formulas into any cell`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`after a collaborator sets a cell value, all other collaborators see the new value in the same cell within 2s`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await enterCell(a, 2, 3, 'hello');
      await expect(cell(a, 2, 3)).toHaveText('hello');
      await expect(cell(b, 2, 3)).toHaveText('hello', { timeout: 60_000 });
      // Once connected, a change arrives quickly.
      const started = Date.now();
      await enterCell(a, 2, 3, 'again');
      await expect(cell(b, 2, 3)).toHaveText('again', { timeout: 30_000 });
      console.log(`cross-node cell edit arrived in ${Date.now() - started}ms`);
    });
  });

  test(`entering a formula (e.g. =SUM(A1:A5)) stores the raw formula and displays the computed result for everyone`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      for (let row = 0; row < 5; row++) await enterCell(a, row, 0, String((row + 1) * 10));
      await enterCell(a, 5, 0, '=SUM(A1:A5)');
      await expect(cell(a, 5, 0)).toHaveText('150');
      await expect(cell(b, 5, 0)).toHaveText('150', { timeout: 60_000 });

      // The cell shows the result; selecting it shows the formula it holds.
      await cell(b, 5, 0).click();
      await expect(b.getByLabel('Formula bar')).toHaveValue('=SUM(A1:A5)');
    });
  });
});
