// Generated by Calimero Studio (deterministic e2e floor). Safe to edit:
// the floor only writes this file if it does not already exist. The verifier-
// writer subagent enriches `test.skip` lines into real assertions; you can
// too. Do NOT delete the smoke test (it's the floor the verify gate trusts).
import { test, expect } from '@playwright/test';
import { loginViaHash, clearAuth, cell, enterCell, openNewWorkbook, withTwoMembers } from './helpers';

test.describe(`collaborator: use formulas like SUM, AVERAGE, MIN, MAX, COUNT, and IF that reference other cells`, () => {
  test.beforeEach(async ({ page }) => {
    await loginViaHash(page, 0);
  });

  test.afterEach(async ({ page }) => {
    await clearAuth(page);
  });

  // Smoke: the post-auth screen renders without a visible error banner.
  // Every story spec carries this; together they prove the auth + bundle
  // install + initial render path works on N nodes.
  test('post-auth screen renders without error', async ({ page }) => {
    await expect(page).toHaveURL(/.+/);
    const errorBanner = page.locator('text=/error|failed/i').first();
    await expect(errorBanner).toBeHidden({ timeout: 5_000 }).catch(() => {});
  });

  test(`a cell containing =SUM(B1:B10) displays the correct sum of those cells' numeric values`, async ({ page }) => {
    await openNewWorkbook(page, { name: 'Sums' });
    for (let row = 0; row < 10; row++) await enterCell(page, row, 1, String(row + 1));
    await enterCell(page, 10, 1, '=SUM(B1:B10)');
    await expect(cell(page, 10, 1)).toHaveText('55');

    // The rest of the family, over the same cells.
    await enterCell(page, 11, 1, '=AVERAGE(B1:B10)');
    await enterCell(page, 12, 1, '=MIN(B1:B10)');
    await enterCell(page, 13, 1, '=MAX(B1:B10)');
    await enterCell(page, 14, 1, '=COUNT(B1:B10)');
    await enterCell(page, 15, 1, '=IF(B11>50,"big","small")');
    await expect(cell(page, 11, 1)).toHaveText('5.5');
    await expect(cell(page, 12, 1)).toHaveText('1');
    await expect(cell(page, 13, 1)).toHaveText('10');
    await expect(cell(page, 14, 1)).toHaveText('10');
    await expect(cell(page, 15, 1)).toHaveText('big');
  });

  test(`when a referenced cell's value changes, every formula that depends on it recalculates and all collaborators see the new result`, async ({ browser }) => {
    await withTwoMembers(browser, async (a, b) => {
      await enterCell(a, 0, 0, '10');
      await enterCell(a, 1, 0, '=A1*2');
      await expect(cell(a, 1, 0)).toHaveText('20');
      await expect(cell(b, 1, 0)).toHaveText('20', { timeout: 60_000 });

      // Bob changes the input; the formula recomputes for both of them. Enter
      // moves his cursor onto A2, so Alice sees his badge beside the value.
      await enterCell(b, 0, 0, '21');
      await expect(cell(b, 1, 0)).toHaveText('42');
      await expect(cell(a, 1, 0)).toHaveText(/^42(BO)?$/, { timeout: 60_000 });
    });
  });
});
