/**
 * Landing content for Mero Design.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { CloudUpload, Cube, Download, FileText, Globe, Grid, LockBox, Refresh, ShieldCheck, WifiOff } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Design",
  packageId: "com.calimero.mero-design",
  tagline: "Collaborative design tool on the Calimero p2p network. Figma-style canvas, your data on your nodes.",
  dir: "mero-design",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Infinite canvas", "Real-time sync", "Files on your nodes"],
  explainer: [
    "A collaborative design tool in the shape of Figma — an infinite canvas with shapes, text and images that several people can work on at once. The difference is where the file lives: in a Calimero context on your infrastructure, shared only with the teammates you invite.",
    "There is no central server holding your designs, which means no vendor with a copy, no seat-based access model, and nothing to migrate off if you change your mind.",
  ],
  features: [
    {
      icon: Grid,
      title: "Infinite canvas",
      body: "Pan and zoom, with multi-select and grouping. Frames and groups ride the same element model.",
    },
    {
      icon: Cube,
      title: "A full shape set",
      body: "Rectangles, circles, lines, arrows and freehand paths, with fill, stroke and corner controls.",
    },
    {
      icon: CloudUpload,
      title: "Images and SVGs",
      body: "Dropped straight onto the canvas and stored as blobs on your node, not on a CDN.",
    },
    {
      icon: FileText,
      title: "Text with font controls",
      body: "Real text elements with family, size and weight, not shapes that happen to look like words.",
    },
    {
      icon: Download,
      title: "Export to PNG or SVG",
      body: "Your work leaves in a format anything can open. No lock-in on the way out.",
    },
    {
      icon: Refresh,
      title: "Real-time sync",
      body: "Changes stream to every member over SSE. No central server arbitrating who edited what.",
    },
  ],
  overview: {
    headline: "Your canvas. Your pixels. Your nodes.",
    showcase: {
      heading: "From a note to a new design, in twenty seconds",
      sub: "Recorded from the real editor on the bundled Web design starter — nothing staged, nothing mocked up.",
      video: {
        src: "/landing/demo.webm",
        poster: "/landing/demo-poster.jpg",
        chapters: [
          { at: 0, title: "Open a board", body: "The design is on your node, and Ada from your team is already in it." },
          { at: 3, title: "Leave a note", body: "Drop a sticky note where the feedback belongs." },
          { at: 9, title: "Point at it", body: "Draw an arrow — it docks to the button it is about." },
          { at: 13.5, title: "Change it", body: "Select the button and give it a new colour. Everyone sees it live." },
          { at: 19, title: "Present it", body: "Hit Present. The change is already in the slide." },
        ],
      },
    },
    comparison: {
      heading: "The design tool, without the landlord",
      sub: "Everything you expect from a collaborative canvas. The difference is who holds the file.",
      themLabel: "A typical cloud design tool",
      rows: [
        { label: "Where the file lives", them: "On the vendor’s servers", us: "On your node, and the nodes of the people you invite" },
        { label: "Who can read it", them: "The vendor, and whoever it grants access", us: "Only members of the board’s namespace" },
        { label: "Adding a collaborator", them: "Another seat on the monthly bill", us: "An invite. The app is open source and free" },
        { label: "Working offline", them: "Usually needs a connection", us: "Full editing; changes merge when you reconnect" },
        { label: "If the vendor goes away", them: "Your files may go with it", us: "Your node still has every board" },
      ],
    },
    collaboration: {
      heading: "Built for editing together, not taking turns",
      sub: "Two people can work on the same board at the same moment and both keep their work, because of how a board is stored.",
      points: [
        { title: "Every element is its own record", body: "Two people editing different shapes never queue behind each other." },
        { title: "Every property is its own value", body: "One person moves a shape while another recolours it, and both changes land." },
        { title: "Presence stays out of the file", body: "Cursors travel separately, so they can never rewrite the artwork." },
        { title: "Offline is a normal state", body: "Keep drawing with no network. Your node merges the changes when it reaches a peer again." },
      ],
      roles: [
        { name: "Owner", can: "Names the board, grants and revokes roles, and can hand ownership on." },
        { name: "Editor", can: "Draws, moves and edits elements, and comments." },
        { name: "Viewer", can: "Follows the board live without changing it." },
      ],
      rolesNote: "Permissions are checked when changes merge, not only hidden in the interface — a rename from a non-owner is refused, wherever it came from.",
    },
    audiences: {
      heading: "For teams whose designs should not live on someone else’s server",
      items: [
        { icon: LockBox, title: "Agencies and studios", body: "Client work under NDA stays on infrastructure you and the client control." },
        { icon: ShieldCheck, title: "Regulated teams", body: "Finance, health and public-sector work that cannot sit on a third-party cloud." },
        { icon: Globe, title: "Open-source projects", body: "A design space the community owns, with no seats to buy and nothing to lose if a vendor changes its terms." },
        { icon: WifiOff, title: "Teams on the move", body: "Keep designing with no connection; boards sync when your devices find each other again." },
      ],
    },
    openSource: {
      commands: [
        "# fork calimero-network/apps on GitHub, then",
        "git clone https://github.com/<you>/apps",
        "cd apps/apps/mero-design",
        "make setup      # build it",
        "make dev-node   # run a local node",
        "make dev        # localhost:5173",
      ],
    },
    alwaysOn: true,
    closing: { title: "Start your first board", body: "Connect a node, or install the desktop app that bundles one, then invite the people you design with." },
  },
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "A board is a shared canvas with real roles on it. Ownership is enforced at merge time, not only in the UI, which is the part worth understanding.",
      ],
      concepts: [
        { term: "Namespace", def: "A design space you own and invite collaborators into." },
        { term: "Context", def: "One board — its elements, comments and cursors." },
        { term: "Element", def: "A shape, a frame, a text node. Stored in a map keyed by id, with each mutable field as its own register so two people editing different properties of the same element do not collide." },
        { term: "Owner / editor / viewer", def: "The three roles. The board name and description live in owner-gated storage: a rename from a non-owner is rejected when the change merges, not merely hidden by the interface." },
        { term: "Cursor", def: "Where each collaborator is pointing. Ephemeral presence, kept apart from the board so a cursor update never touches your artwork." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node and choose your node in the popup." },
        { title: "Create a board", body: "You are its owner. Name it, and set a description if it needs one." },
        { title: "Draw something", body: "Add frames, shapes and text. Each element is a separate record, so collaborators editing different elements never queue behind each other." },
        { title: "Invite editors", body: "Grant the editor role to the people who should be able to change things; everyone else can look." },
      ],
    },
    {
      id: "sharing",
      heading: "Working together",
      paragraphs: [
        "Roles are granted and revoked by the owner, and ownership itself can be transferred. Comments carry their author, and only that author may edit or delete their own.",
        "Layer order, grouping and multi-select all operate on the same element records, so two people rearranging different groups converge without either losing a move.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Elements, keyed by id, with per-field registers for position, style, text and label.",
        "Comments and replies, each owned by its author.",
        "Members and their usernames, plus the role list.",
        "Cursors, as presence — deliberately not part of the document.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "A rename did not stick", def: "The board name is owner-gated. A non-owner’s rename is refused at merge, so it can appear locally for a moment and then revert." },
        { term: "You cannot edit", def: "You have the viewer role. Ask the owner to grant editor." },
        { term: "Cursors are frozen", def: "Presence stopped, not the board. Your elements are unaffected; reconnecting restores cursors." },
      ],
    },
  ],
  previewSteps: [
    { title: "A board with tools", body: "Frames, shapes and text, each stored as its own record rather than one blob." },
    { title: "Two people editing", body: "Separate elements mean separate records, so concurrent edits merge instead of overwriting." },
    { title: "Properties change live", body: "Every mutable field is its own register — moving a shape does not conflict with recolouring it." },
    { title: "Cursors alongside", body: "Presence rides separately from the document, so it can never rewrite the artwork." },
  ],
  loginPopup: LoginPopup,
};
