/**
 * Landing content for Mero Design.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { CloudUpload, Cube, Download, FileText, Grid, Refresh } from '@calimero-network/mero-icons';

import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Design",
  packageId: "com.calimero.mero-design",
  tagline: "Collaborative design tool on the Calimero p2p network. Figma-style canvas, your data on your nodes.",
  dir: "mero-design",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Infinite canvas", "Real-time sync", "Files on your nodes"],
  explainer: [
    "A collaborative design tool in the shape of Figma — an infinite canvas with shapes, text and images that several people can work on at once. The difference is where the file lives: in a Calimero context on your infrastructure, shared only with the teammates you invite.",
    "There is no central server holding your designs, which means no vendor with a copy, no seat-based access model, and nothing to migrate off if you change your mind.",
  ],
  features: [
    {
      icon: Grid,
      title: "Infinite canvas",
      body: "Pan and zoom, with multi-select and grouping. Frames and groups ride the same element model.",
    },
    {
      icon: Cube,
      title: "A full shape set",
      body: "Rectangles, circles, lines, arrows and freehand paths, with fill, stroke and corner controls.",
    },
    {
      icon: CloudUpload,
      title: "Images and SVGs",
      body: "Dropped straight onto the canvas and stored as blobs on your node, not on a CDN.",
    },
    {
      icon: FileText,
      title: "Text with font controls",
      body: "Real text elements with family, size and weight, not shapes that happen to look like words.",
    },
    {
      icon: Download,
      title: "Export to PNG or SVG",
      body: "Your work leaves in a format anything can open. No lock-in on the way out.",
    },
    {
      icon: Refresh,
      title: "Real-time sync",
      body: "Changes stream to every member over SSE. No central server arbitrating who edited what.",
    },
  ],
};
