/**
 * Landing content for Mero PixArt.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { Circle, Cube3D, Cube3DLayers, Eye, LineChart, Zap } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero PixArt",
  packageId: "com.calimero.mero-pixart",
  tagline: "Collaborative p2p image editor on the Calimero network. Photoshop-style layers, masks, and adjustments — your pixels on your nodes.",
  dir: "mero-pixart",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Non-destructive edits", "Real layer folders", "Pixels on your nodes"],
  explainer: [
    "A collaborative raster image editor with the depth of a desktop tool — layer folders, masks, blend modes, curves and a corner-pin warp — that several people can work in at the same time.",
    "Adjustments are non-destructive and applied live, so you can reconsider an exposure change a week later. The project, including every uploaded image, lives as blobs on your node rather than in a cloud editor’s bucket.",
  ],
  features: [
    {
      icon: Cube3DLayers,
      title: "Layers and folders",
      body: "Raster, text and fill layers inside real collapsible folders, not a flat list pretending to nest.",
    },
    {
      icon: Zap,
      title: "Non-destructive adjustments",
      body: "Brightness, contrast, saturation, hue, exposure, blur and invert, applied live and always reversible.",
    },
    {
      icon: LineChart,
      title: "Curves",
      body: "A per-channel RGB spline editor applied through a lookup table, the way a real editor does it.",
    },
    {
      icon: Eye,
      title: "Blend modes and masks",
      body: "All sixteen blend modes, per-layer opacity, and paintable masks to hide or reveal.",
    },
    {
      icon: Cube3D,
      title: "Free transform",
      body: "Move, scale, rotate, shear, mirror, and a corner-pin warp for perspective.",
    },
    {
      icon: Circle,
      title: "Paint tools",
      body: "Brush, eraser, bucket fill and eyedropper, each re-rendering the layer to a new blob.",
    },
  ],
  overview: {
    headline: "Your images. Your layers. Your nodes.",
    showcase: {
      heading: "A launch poster, edited in layers",
      sub: "Recorded from the real editor on the bundled Aurora Edition project: 23 layers in six folders, all drawn by the app’s own compositor.",
      video: {
        src: "/landing/demo.webm",
        poster: "/landing/demo-poster.jpg",
        chapters: [
          { at: 0, title: "Open a project", body: "A finished poster on your node, in folders, with Ada from your team already in it." },
          { at: 3.5, title: "Adjust, non-destructively", body: "Swing the backdrop’s hue and saturation. They are stored as settings, so the pixels underneath never change." },
          { at: 8.5, title: "Change a blend mode", body: "Set the brightest ribbon to Multiply and it sinks into the night sky, then back to Screen." },
          { at: 12, title: "Hide a whole folder", body: "One eye hides the product card and everything in it. Nothing is deleted." },
          { at: 15.5, title: "Paint on a new layer", body: "Add a raster layer and draw a stroke. It lands on that layer alone." },
        ],
      },
    },
    comparison: {
      heading: "An image editor, without the landlord",
      sub: "Layers, masks, blend modes and curves, the way a desktop editor does them. The difference is where the file lives.",
      themLabel: "A typical cloud image editor",
      rows: [
        { label: "Where the file lives", them: "On the vendor’s servers", us: "On your node, and the nodes of the people you invite" },
        { label: "Your uploaded images", them: "In the vendor’s storage bucket", us: "Stored as blobs on your node" },
        { label: "Who can open it", them: "The vendor, and whoever it grants access", us: "Only members of the project’s namespace" },
        { label: "Adding a collaborator", them: "Another seat on the monthly bill", us: "An invite. The app is open source and free" },
        { label: "Getting your work out", them: "Often a proprietary format", us: "Export PNG, JPEG or SVG whenever you want" },
      ],
    },
    collaboration: {
      heading: "Several people, one image, no server in the middle",
      sub: "Everyone in a project sees each other’s cursors and changes, and two people can work on it at once without either losing work, because of how a document is stored.",
      points: [
        { title: "Every layer is its own record", body: "Two people working on different layers never queue behind each other." },
        { title: "Pixels, mask, transform and adjustments are separate", body: "One person paints on a layer while another moves it or tunes its curves, and both changes land." },
        { title: "Adjustments are settings, not pixels", body: "They are applied when the image is drawn, so undoing a change never needs the original back from anyone." },
        { title: "Presence stays out of the file", body: "Cursors travel separately from the document, so they can never touch the artwork." },
      ],
      roles: [
        { name: "Owner", can: "Names the document, sets its size and background, grants and revokes the editor role, and can hand ownership on." },
        { name: "Editor", can: "Adds, paints, transforms, adjusts and deletes layers." },
        { name: "Viewer", can: "Watches the image change without being able to change it." },
      ],
      rolesNote: "The contract checks these, not just the interface: a layer change from a viewer, or a rename from a non-owner, is refused wherever it came from.",
    },
    audiences: {
      heading: "Made for images that are nobody else’s business",
      items: [
        { label: "Design & marketing teams", title: "Campaign artwork that stays off a vendor’s cloud until launch day", body: "Posters, ads and social assets built in layers and folders by the whole team, on your own nodes.", uses: ["Layer folders", "Blend modes", "PNG and JPEG export"] },
        { label: "Photographers & retouchers", title: "Non-destructive edits you can revisit a week later", body: "Curves, exposure and masks are stored as settings, so a client’s change of mind is a slider, not a redo.", uses: ["Curves", "Paintable masks", "Adjustments"] },
        { label: "Agencies & freelancers", title: "Client work shared with the client, and nobody else", body: "Invite the client as a viewer to watch the image take shape, or as an editor to work on it with you.", uses: ["Owner, editor and viewer roles", "Live cursors", "Invite links"] },
        { label: "Open-source communities", title: "An image editor the community owns", body: "No seats and no terms that can change under you. If a tool is missing, fork it and add it.", uses: ["Free for everyone", "MIT or Apache-2.0", "Fork and customise"] },
      ],
    },
    openSource: {
      license: "MIT or Apache-2.0",
      commands: [
        "# fork calimero-network/apps on GitHub, then",
        "git clone https://github.com/<you>/apps",
        "cd apps/apps/mero-pixart",
        "make setup   # check tools, build logic, install app deps",
        "make dev     # 2 local nodes + app on :5176",
      ],
    },
    alwaysOn: true,
    closing: { title: "Start your first image", body: "Connect a node, or install the desktop app that bundles one, then invite the people you make things with." },
  },
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "A genuinely deep raster editor — layers, masks, blend modes, curves — that several people can work in at once. The reason that is possible is that a document is a set of layer records, not one image file.",
      ],
      concepts: [
        { term: "Namespace", def: "A workspace you own and invite collaborators into." },
        { term: "Context", def: "One document: its canvas size, its layers, its members and their cursors." },
        { term: "Layer", def: "A record in a map keyed by layer id — raster, text or fill. Content, mask, transform and adjustments are separate fields, so painting on a layer does not conflict with moving it." },
        { term: "Adjustment", def: "Non-destructive. Brightness, contrast, saturation, hue, exposure, blur and invert are stored as parameters and applied at render time, so the pixels underneath are never rewritten." },
        { term: "Owner / editor", def: "The document name and description are owner-gated: a rename from a non-owner is rejected when it merges, not merely hidden." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node and pick your node." },
        { title: "Create a document", body: "Choose a canvas size. You are the owner." },
        { title: "Work in layers", body: "Add raster, text and fill layers, group them in folders, and reorder freely." },
        { title: "Invite editors", body: "Grant the editor role. Everyone else can watch the document change without being able to change it." },
      ],
    },
    {
      id: "sharing",
      heading: "Working together",
      paragraphs: [
        "Because each layer is its own record with separate fields, two people working on different layers never contend, and two people doing different things to one layer — one painting, one transforming — usually do not either.",
        "Cursors are presence, kept apart from the document, so watching someone move never touches the artwork.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Canvas size and background.",
        "Layers, keyed by id, with content, mask, transform, adjustments and text as separate fields.",
        "Members and their usernames, plus roles.",
        "Cursors, as presence.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "A layer jumped back", def: "Two people moved the same layer. The transform is one field and converges to the later move; the pixels are untouched." },
        { term: "An adjustment looks different on their screen", def: "Adjustments render from parameters, so a difference means one node has not received the latest parameter yet. It resolves on sync." },
        { term: "You cannot edit", def: "You hold the viewer role. Ask the owner for editor." },
      ],
    },
  ],
  previewSteps: [
    { title: "Paint on the canvas", body: "Pick a colour and drag, or use the arrow keys and Space. The stroke lands on the layer you have selected." },
    { title: "Ada draws at the same time", body: "Your teammate paints on her own layer. Neither of you waits for the other, because every layer is a separate record." },
    { title: "Hide a layer", body: "Each eye hides one layer and leaves the others exactly as they were." },
    { title: "Tune the hue", body: "The slider is an adjustment on the selected layer: stored as a setting, so Reset brings the original pixels straight back." },
  ],
  loginPopup: LoginPopup,
};
