/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Comment {
  doc_id: string;
  body: string;
  created_at: number;
}

export interface CommentDto {
  id: string;
  doc_id: string;
  body: string;
  created_at: number;
}

export interface DocDto {
  id: string;
  title: string;
  content: string;
  tags: string[];
  archived: boolean;
  created_at: number;
  updated_at: number;
}

export interface DocRecord {
  title: string;
  content: string;
  tags: string[];
  archived: boolean;
  created_at: number;
  updated_at: number;
  content_updates: CalimeroBytes[];
}

export interface DocsState {
  docs: Record<string, DocRecord>;
  next_id: {  };
  comments: Record<string, Comment>;
  next_comment_id: {  };
  default_sort_order: string;
}

export interface Event_CommentAdded {
  id: string;
}

export interface Event_CommentDeleted {
  id: string;
}

export interface Event_CommentEdited {
  id: string;
}

export interface Event_DocArchived {
  id: string;
}

export interface Event_DocCreated {
  id: string;
}

export interface Event_DocDeleted {
  id: string;
}

export interface Event_DocEdited {
  id: string;
}

export interface Event_DocTagsChanged {
  id: string;
}

export interface Event_DocUnarchived {
  id: string;
}

export interface Event_Migrated {
  from_version: string;
  to_version: string;
}











export type AbiEvent =
  | { name: "DocCreated"; payload: Event_DocCreated }
  | { name: "DocEdited"; payload: Event_DocEdited }
  | { name: "DocArchived"; payload: Event_DocArchived }
  | { name: "DocUnarchived"; payload: Event_DocUnarchived }
  | { name: "DocDeleted"; payload: Event_DocDeleted }
  | { name: "DocTagsChanged"; payload: Event_DocTagsChanged }
  | { name: "CommentAdded"; payload: Event_CommentAdded }
  | { name: "CommentEdited"; payload: Event_CommentEdited }
  | { name: "CommentDeleted"; payload: Event_CommentDeleted }
  | { name: "Migrated"; payload: Event_Migrated }
;


/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === "string") {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || []
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

/**
 * Convert CalimeroBytes instances to arrays for WASM compatibility
 */
function convertCalimeroBytesForWasm(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (obj instanceof CalimeroBytes) {
    return obj.toArray();
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertCalimeroBytesForWasm(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertCalimeroBytesForWasm(value);
    }
    return result;
  }

  return obj;
}

/**
 * Convert arrays back to CalimeroBytes instances from WASM responses
 */
function convertWasmResultToCalimeroBytes(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (Array.isArray(obj) && obj.every(item => typeof item === "number")) {
    return new CalimeroBytes(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertWasmResultToCalimeroBytes(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertWasmResultToCalimeroBytes(value);
    }
    return result;
  }

  return obj;
}

export class DocsClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_doc
   */
  public async createDoc(params: { title: string; content: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * get_doc
   *
   * @intent read_only
   */
  public async getDoc(params: { id: string }): Promise<DocDto> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as DocDto;
  }

  /**
   * list_docs
   *
   * @intent read_only
   */
  public async listDocs(params: { include_archived: boolean }): Promise<DocDto[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_docs', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as DocDto[];
  }

  /**
   * edit_doc
   */
  public async editDoc(params: { id: string; title: string | null; content: string | null }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * append_doc_update
   */
  public async appendDocUpdate(params: { id: string; update: CalimeroBytes }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'append_doc_update', argsJson: convertCalimeroBytesForWasm(params), executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_doc_updates
   *
   * @intent read_only
   */
  public async getDocUpdates(params: { id: string }): Promise<CalimeroBytes[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_doc_updates', argsJson: params, executorPublicKey: this._executorPublicKey });
    return convertWasmResultToCalimeroBytes(response) as CalimeroBytes[];
  }

  /**
   * archive_doc
   */
  public async archiveDoc(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'archive_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * unarchive_doc
   */
  public async unarchiveDoc(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'unarchive_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_doc
   */
  public async deleteDoc(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * add_tag
   */
  public async addTag(params: { id: string; tag: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_tag', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * remove_tag
   */
  public async removeTag(params: { id: string; tag: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'remove_tag', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * add_comment
   */
  public async addComment(params: { doc_id: string; body: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * list_comments
   *
   * @intent read_only
   */
  public async listComments(params: { doc_id: string }): Promise<CommentDto[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_comments', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as CommentDto[];
  }

  /**
   * get_comment
   *
   * @intent read_only
   */
  public async getComment(params: { id: string }): Promise<CommentDto> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as CommentDto;
  }

  /**
   * comment_count
   *
   * @intent read_only
   */
  public async commentCount(): Promise<number> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'comment_count', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as number;
  }

  /**
   * comment_schema_version
   *
   * @intent read_only
   */
  public async commentSchemaVersion(params: { id: string }): Promise<number> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'comment_schema_version', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as number;
  }

  /**
   * edit_comment
   */
  public async editComment(params: { id: string; body: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_comment
   */
  public async deleteComment(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_comment', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * default_sort_order
   *
   * @intent read_only
   */
  public async defaultSortOrder(): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'default_sort_order', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

}