/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface DocDto {
  id: string;
  title: string;
  content: string;
  tags: string[];
  archived: boolean;
  created_at: number;
  updated_at: number;
}

export interface DocRecord {
  title: string;
  content: string;
  tags: string[];
  archived: boolean;
  created_at: number;
  updated_at: number;
}

export interface DocsState {
  docs: Record<string, DocRecord>;
  next_id: {  };
}

export interface Event_DocArchived {
  id: string;
}

export interface Event_DocCreated {
  id: string;
}

export interface Event_DocDeleted {
  id: string;
}

export interface Event_DocEdited {
  id: string;
}

export interface Event_DocTagsChanged {
  id: string;
}

export interface Event_DocUnarchived {
  id: string;
}







export type AbiEvent =
  | { name: "DocCreated"; payload: Event_DocCreated }
  | { name: "DocEdited"; payload: Event_DocEdited }
  | { name: "DocArchived"; payload: Event_DocArchived }
  | { name: "DocUnarchived"; payload: Event_DocUnarchived }
  | { name: "DocDeleted"; payload: Event_DocDeleted }
  | { name: "DocTagsChanged"; payload: Event_DocTagsChanged }
;


export class DocsClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_doc
   */
  public async createDoc(params: { title: string; content: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * get_doc
   */
  public async getDoc(params: { id: string }): Promise<DocDto> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as DocDto;
  }

  /**
   * list_docs
   */
  public async listDocs(params: { include_archived: boolean }): Promise<DocDto[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'list_docs', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as DocDto[];
  }

  /**
   * edit_doc
   */
  public async editDoc(params: { id: string; title: string | null; content: string | null }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'edit_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * archive_doc
   */
  public async archiveDoc(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'archive_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * unarchive_doc
   */
  public async unarchiveDoc(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'unarchive_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * delete_doc
   */
  public async deleteDoc(params: { id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'delete_doc', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * add_tag
   */
  public async addTag(params: { id: string; tag: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'add_tag', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * remove_tag
   */
  public async removeTag(params: { id: string; tag: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'remove_tag', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

}