/**
 * Landing content for Mero Chess.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { ArrowUpRight, CloudX, ExternalLink, LockCheck, Target } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Chess",
  packageId: "com.calimero.mero-chess",
  tagline: "Two-player chess with no game server. A table is a Calimero context: the move list replicates as CRDT state and the rules — legal moves, check, mate, the draws — run inside the contract on both players' own nodes.",
  dir: "mero-chess",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["No game server", "Rules run in the contract", "No accounts"],
  explainer: [
    "Two-player chess where the board is not hosted anywhere. A table is a Calimero context holding two seats and a list of moves, and it replicates between the two players’ own nodes — so a game is a thing the two of you have, not a row in somebody else’s database.",
    "The rules live in the contract rather than in either client: legal moves, check, mate, castling, en passant, promotion, and every one of the draws. Your client asks the contract what it may play and gets a list back, which is why the board never offers a move the node would refuse — and why a modified client cannot cheat.",
  ],
  features: [
    {
      icon: CloudX,
      title: "No game server",
      body: "A table is a context. Two nodes hold the same move list and nobody hosts a game.",
    },
    {
      icon: LockCheck,
      title: "The contract is the referee",
      body: "Every rule is enforced inside the WASM contract, on both players’ nodes. A client that asks for an illegal move is simply told no.",
    },
    {
      icon: Target,
      title: "Moves, never a board",
      body: "State is the move list keyed by ply. Two people moving at once resolve to one move — the same one on every node.",
    },
    {
      icon: ArrowUpRight,
      title: "Results nobody writes down",
      body: "Checkmate, stalemate and the repetition rules are derived from the moves, so the result cannot disagree with the game.",
    },
    {
      icon: ExternalLink,
      title: "Invite by link",
      body: "One link opens the table. No sign-up, no account, no email address — and whoever opens it can play or watch.",
    },
  ],
  faq: [
    {
      q: "Can my opponent cheat with a modified client?",
      a: "No. Nothing about the game is decided in the browser: every move is validated by the contract running on your node as well as theirs, and a move your node rejects never becomes part of the game.",
    },
    {
      q: "What happens if we both move at the same time?",
      a: "Only one of you can take that ply. Moves are keyed by ply number and merge to a single winner by a rule every node applies identically, so the two boards agree — the move that lost simply never happened.",
    },
    {
      q: "Is there a clock?",
      a: "No. Games here are correspondence-paced: the table keeps the move list and the players’ presence, and there is no time control to run out of while your laptop is shut.",
    },
    {
      q: "Can other people watch?",
      a: "Yes. Anyone in the namespace can open the table; the two seats are taken but the board and the moves are visible to everyone, which is what a game of complete information should be.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "A game of chess is a Calimero context. There is no server keeping the board: each player’s own node runs the contract, holds the move list, and replicates it to the other. The rules — legal moves, check, mate, the draws — are inside that contract, so the node you are talking to is the referee, and so is theirs.",
      ],
      concepts: [
        { term: "Namespace", def: "A club. You create one, invite the people you play with, and every table inside it is open to them without another invitation." },
        { term: "Context", def: "A table. It holds the seats, the move list and the record of every game played at it — one board, as many games as you like." },
        { term: "Seat", def: "White or black. The first person to claim a chair holds it; the colours swap on every rematch, the way they do across a real board." },
        { term: "The move list", def: "The whole of the game state. Nothing stores a board: every reader replays the moves from the starting array, which is why two nodes cannot disagree about the position." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node. The Calimero desktop app bundles one; if you run your own, enter its URL in the same popup." },
        { title: "Open a table", body: "A new table is a context in a namespace you own. Joining someone else’s means opening their invite link." },
        { title: "Take a seat", body: "Claim white or black and give yourself a name. The game begins when both chairs are taken." },
        { title: "Play", body: "Click a piece and then a square. The squares offered are the legal moves the contract handed your client, so the board never shows a move the node would refuse." },
      ],
    },
    {
      id: "sharing",
      heading: "Playing with someone else",
      paragraphs: [
        "Invitations are links. There is no account, no email address and no sign-up: opening the link and connecting a node is the whole of joining, and whoever opens it can take the free seat or watch.",
        "The invitation admits someone to the namespace the table lives in, so one link is enough for every table in that namespace — a club rather than a single game.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "The move list, keyed by game and ply. Each entry holds the move in UCI, its notation, who played it and when.",
        "The two seats, each recording who claimed it and at what moment. First claim wins, and every node resolves that the same way.",
        "Endings that a PERSON caused: a resignation, an agreed draw, a claimed one. Checkmate, stalemate, a dead position and the repetition rules are derived from the moves instead, so nothing writes them down and nothing can disagree with the board.",
        "Nothing is private here. Chess is a game of complete information, so everything in the state is meant to be seen by both players.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "Your move is refused", def: "The contract refuses a move that is not legal, is out of turn, or arrives in a finished game — and it says which. If the board offered the square, your client is reading a position the node has already moved past; it re-reads after every call." },
        { term: "The other player looks offline", def: "Presence expires after thirty seconds without a call from their node. It means \"not heard from\", not \"gone\": their moves still arrive when their node reconnects." },
        { term: "You both moved at once", def: "Only one of the two can take the ply, and every node picks the same one. The move that lost is simply not in the game — play it again if it is still legal." },
        { term: "The invite link does nothing", def: "An invitation is tied to the namespace that minted it. Ask for a fresh one rather than reusing an old link." },
      ],
    },
  ],
  previewSteps: [
    { title: "A board that is a context", body: "Two seats and a move list, replicated between the two players’ own nodes. Nothing in the middle, and nothing to host." },
    { title: "The contract knows the rules", body: "Your client asks for the legal moves rather than working them out, so the squares it offers are the squares the node will accept." },
    { title: "A move replicates", body: "Moves are keyed by ply. Two players moving in the same instant resolve to one move, the same one on both nodes." },
    { title: "The result is derived", body: "Nobody writes down \"checkmate\": both nodes replay the same moves and reach the same verdict, which is what makes it trustworthy without a referee." },
  ],
  loginPopup: LoginPopup,
};
