#!/usr/bin/env python3
"""Assert no tracked file under apps/mero-docs contains an em dash (U+2014).

WHY THIS EXISTS

The copy-lint vitest suite only scans string literals and JSX text in a
handful of .tsx/.ts files, so an em dash in a comment, a test name, a Rust
doc comment or a merobox YAML step slips past it every time. This checks
every tracked text file in the app instead of relying on reviewers to catch
what a narrower, code-shaped lint cannot see.

Skips a file whose first line marks it generated (`@generated` or
`DO NOT EDIT`, e.g. `src/generated/**`), and the landing page directory,
which is a verbatim copy of `scripts/landing/template` regenerated by
`pnpm landing:generate` - fixing its copy without the template just makes
the next regen re-introduce the em dash.
"""

import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCOPE = "apps/mero-docs"
EM_DASH = chr(0x2014)

# Whole subtrees this check does not read at all; see the module docstring.
EXCLUDED_DIRS = ("apps/mero-docs/app/src/pages/landing/",)


def is_generated(text: str) -> bool:
    first_line = text.split("\n", 1)[0]
    return "@generated" in first_line or "DO NOT EDIT" in first_line


def main() -> int:
    files = subprocess.run(
        ["git", "ls-files", SCOPE],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()

    violations = []
    for rel_path in files:
        if any(rel_path.startswith(d) for d in EXCLUDED_DIRS):
            continue
        try:
            text = (ROOT / rel_path).read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue  # binary asset (png/ico/...)
        if is_generated(text):
            continue
        for lineno, line in enumerate(text.split("\n"), start=1):
            if EM_DASH in line:
                violations.append(f"{rel_path}:{lineno}: {line.strip()}")

    if violations:
        print('::error::em dash (U+2014) found - replace with a plain "-":')
        for violation in violations:
            print(violation)
        return 1

    print(f"no em dash in {len(files)} tracked files under {SCOPE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
