/**
 * Landing content for Mero CRM.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { BarChart, Clock, Refresh, Shield, Target, Zap } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero CRM",
  packageId: "com.calimero.mero-crm",
  tagline: "A simple, private sales CRM - track your pipeline, work your deals, and never lose a follow-up",
  dir: "mero-crm",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  themeStorageKey: "app:theme",
  trust: ["Pipeline on your nodes", "Built-in deal assistant", "No per-seat vendor"],
  explainer: [
    "A sales CRM with only the parts that close deals: a visual pipeline, deals with a value and a next step, the people behind them, and a to-do list that puts overdue follow-ups first. Everything a tool like Pipedrive is used for day to day, without the forty menus around it.",
    "The pipeline lives in a Calimero context your team shares, replicated between your own nodes. Your customer list is the most sensitive thing a sales team owns, and here there is no vendor holding a copy of it.",
  ],
  features: [
    {
      icon: Target,
      title: "Visual pipeline",
      body: "Drag deals between stages, or onto Won and Lost. Every column shows its count, value and weighted forecast.",
    },
    {
      icon: Zap,
      title: "Deal assistant",
      body: "A health score for every deal, the next best step in one click, a follow-up email draft, and a ready prompt for your AI.",
    },
    {
      icon: Clock,
      title: "Never miss a follow-up",
      body: "Calls, meetings, tasks and deadlines, grouped by overdue, today and upcoming. Idle deals are flagged as rotting.",
    },
    {
      icon: Refresh,
      title: "Automations",
      body: "When a deal enters a stage, the follow-up is scheduled for its owner automatically.",
    },
    {
      icon: BarChart,
      title: "Insights",
      body: "Open and weighted pipeline, win rate, sales cycle, forecast by close month, and why deals are lost.",
    },
    {
      icon: Shield,
      title: "Your customers stay yours",
      body: "The pipeline replicates between your team’s nodes. There is no vendor database to breach or to price you out of.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "The model is deliberately small: a pipeline of stages, deals moving through them, the people behind the deals, and the activities that move them forward.",
      ],
      concepts: [
        { term: "Namespace", def: "Your sales team. Its members are the people who can see and work the pipelines." },
        { term: "Pipeline", def: "One sales process — say New business or Renewals — and one Calimero context. It holds its stages, deals, people, activities, notes and automations." },
        { term: "Stage", def: "A column of the pipeline with a win probability. The probability is what turns a pipeline total into a weighted forecast." },
        { term: "Deal", def: "An opportunity with a value, an owner, a contact person and an expected close date. Every field is its own register, so two people editing different fields never collide." },
        { term: "Activity", def: "A call, meeting, task, email or deadline, due on a date. The earliest open one is the deal’s next step." },
        { term: "Rotting", def: "An open deal nobody has touched for longer than the pipeline allows (14 days by default). It is flagged on the board." },
        { term: "Automation", def: "A rule of the form “when a deal enters this stage, schedule this activity”. It runs inside the contract, so it fires whoever moves the deal." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Connect a node", body: "Press Connect to node and pick your node in the popup." },
        { title: "Create a workspace and a pipeline", body: "A workspace for the team, then a pipeline with its currency. It starts with five stages you can rename, reorder and re-weight in Settings." },
        { title: "Add your deals", body: "Press N anywhere. Only a title is required; the value accepts shorthand like 12k." },
        { title: "Work the board", body: "Drag deals forward, schedule the next step on each, and let the Activities list tell you what is due today." },
      ],
    },
    {
      id: "sharing",
      heading: "The deal assistant",
      paragraphs: [
        "Every open deal gets a health score from the signals a sales manager checks by eye: is there a next step, is it overdue, has anyone touched the deal lately, has the close date slipped, is there a contact person.",
        "From those it suggests the next best step for the deal’s stage — a discovery call, a demo, the proposal, the follow-up — and schedules it in one click. It also drafts a stage-appropriate follow-up email.",
        "The assistant runs in your browser on your own data; nothing is sent anywhere. For open-ended coaching, Copy AI coaching prompt packages the deal’s context for whichever AI assistant you already use.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Stages, deals, people, activities, notes and automations, each in its own map keyed by id, in the pipeline’s context.",
        "Every mutable field as its own last-writer-wins register; edits only write the fields that changed, so a teammate’s concurrent edit to another field survives.",
        "Money as whole units of the pipeline currency, never floats, so every node computes identical totals.",
        "Only a deal’s creator can delete it, and only a note’s author can delete the note — enforced in the contract, not the UI.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "A stage will not delete", def: "It still has open deals. Move them to another stage, or close them, first." },
        { term: "A deal cannot be dragged", def: "Closed deals leave the board. Reopen it from its page to put it back in the stage it closed from." },
        { term: "A teammate’s move has not shown up", def: "Their node is behind or offline. The board catches up on sync without any action." },
      ],
    },
  ],
  previewSteps: [
    { title: "A pipeline of stages", body: "Five columns, each with its count, value and weighted forecast — replicated to every member, with no server hosting it." },
    { title: "A deal moves", body: "The stage is one register on the deal. Moving it collides with nothing else on the card." },
    { title: "A follow-up appears", body: "Entering Proposal fired an automation, and the owner now has “Send the proposal” due tomorrow." },
    { title: "The assistant flags a deal", body: "No activity in three weeks and a slipped close date: the card is marked rotting, with the next step one click away." },
  ],
  loginPopup: LoginPopup,
};
