/**
 * Landing content for Mero Issue Tracker.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { FileCheck, Package, Refresh, Shield, Zap } from '@calimero-network/mero-icons';

import Animation from './animation';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Issue Tracker",
  packageId: "com.calimero.mero-issue-tracker",
  tagline: "A private, real-time issue board for a small engineering team - create, triage, and discuss issues together",
  dir: "mero-issue-tracker",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["Structured issues", "MCP server included", "Private to your team"],
  explainer: [
    "A real-time issue board for a small engineering team. Issues are structured around what actually makes a bug actionable — a summary, who it affects, how to reproduce it, and what \"fixed\" has to satisfy — rather than a free-text box and a pile of labels.",
    "It also ships an MCP server, so an AI coding agent can pull an issue with its full context and hand you back a fix. The board is private to your namespace, not a tenant in someone else’s SaaS.",
  ],
  features: [
    {
      icon: FileCheck,
      title: "Structured issues",
      body: "Summary, impact, reproduction steps and resolution criteria — the four things that make a bug fixable.",
    },
    {
      icon: Refresh,
      title: "Real-time board",
      body: "Triage together. Status moves and comments land on every member’s node as they happen.",
    },
    {
      icon: Zap,
      title: "Copy fix prompt",
      body: "Render any issue as a prompt for a coding agent, with its context attached, in one click.",
    },
    {
      icon: Package,
      title: "MCP server",
      body: "Expose the board to an AI agent over Model Context Protocol, so it can read issues directly.",
    },
    {
      icon: Shield,
      title: "Private to your team",
      body: "A namespace you own, not a workspace in a product that reserves the right to read it.",
    },
  ],
  animation: Animation,
};
