/**
 * Landing content for Mero Stream.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { ArrowsUpDown, BarChart, CheckSquare, Trash } from '@calimero-network/mero-icons';

import Animation from './animation';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Stream",
  packageId: "com.calimero.mero-stream",
  tagline: "Capacity probe: streaming media OVER Calimero. /stream runs a toy codec inside the WASM app (approach 3); /live stores opaque browser-encoded H.264 (approach 2). Experimental; not shippable media.",
  dir: "mero-stream",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web",
  experimental: true,
  trust: ["Measured, not promised", "Deterministic codec", "Web only"],
  explainer: [
    "An honest experiment rather than a finished product: how far can the Calimero network carry live video? Mero Stream exists to find the ceiling and report it, and the number it produces is the point.",
    "There are two paths. One runs a deliberately simple integer-only codec inside the WASM app itself; the other stores browser-encoded H.264 fragments and treats the network as transport. Comparing them is what makes the limit legible.",
  ],
  features: [
    {
      icon: ArrowsUpDown,
      title: "Two codec paths",
      body: "A deterministic codec inside the WASM app, or browser WebCodecs H.264 through the same context.",
    },
    {
      icon: BarChart,
      title: "Measured, not promised",
      body: "Built to find the real capacity ceiling and report it, rather than to claim one.",
    },
    {
      icon: CheckSquare,
      title: "Deterministic by construction",
      body: "Integer-only, with no float, no SIMD and no threads, so every peer decodes identically.",
    },
    {
      icon: Trash,
      title: "Delete is a tombstone",
      body: "Fragment keys are monotone and never reused, so a deletion cannot be confused with a gap.",
    },
  ],
  faq: [
    {
      q: "Is this production-ready?",
      a: "No, and it does not claim to be. Mero Stream is a capacity probe: it exists to measure how much live media a Calimero context can carry. Treat its numbers as findings, not guarantees.",
    },
    {
      q: "Why web only?",
      a: "Not because it breaks on the desktop — it renders and runs there. What is unsupported is the desktop integration around it, so anything you see in a desktop window should be reproduced in a browser before it is believed.",
    },
  ],
  animation: Animation,
};
