/**
 * Landing content for Mero Stream.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { ArrowsUpDown, BarChart, CheckSquare, Trash } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Stream",
  packageId: "com.calimero.mero-stream",
  tagline: "Capacity probe: streaming media OVER Calimero. /stream runs a toy codec inside the WASM app (approach 3); /live stores opaque browser-encoded H.264 (approach 2). Experimental; not shippable media.",
  dir: "mero-stream",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web",
  experimental: true,
  trust: ["Measured, not promised", "Deterministic codec", "Web only"],
  explainer: [
    "An honest experiment rather than a finished product: how far can the Calimero network carry live video? Mero Stream exists to find the ceiling and report it, and the number it produces is the point.",
    "There are two paths. One runs a deliberately simple integer-only codec inside the WASM app itself; the other stores browser-encoded H.264 fragments and treats the network as transport. Comparing them is what makes the limit legible.",
  ],
  features: [
    {
      icon: ArrowsUpDown,
      title: "Two codec paths",
      body: "A deterministic codec inside the WASM app, or browser WebCodecs H.264 through the same context.",
    },
    {
      icon: BarChart,
      title: "Measured, not promised",
      body: "Built to find the real capacity ceiling and report it, rather than to claim one.",
    },
    {
      icon: CheckSquare,
      title: "Deterministic by construction",
      body: "Integer-only, with no float, no SIMD and no threads, so every peer decodes identically.",
    },
    {
      icon: Trash,
      title: "Delete is a tombstone",
      body: "Fragment keys are monotone and never reused, so a deletion cannot be confused with a gap.",
    },
  ],
  faq: [
    {
      q: "Is this production-ready?",
      a: "No, and it does not claim to be. Mero Stream is a capacity probe: it exists to measure how much live media a Calimero context can carry. Treat its numbers as findings, not guarantees.",
    },
    {
      q: "Why web only?",
      a: "Not because it breaks on the desktop — it renders and runs there. What is unsupported is the desktop integration around it, so anything you see in a desktop window should be reproduced in a browser before it is believed.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "Mero Stream is a capacity probe, not a finished product, and this page would rather say so than oversell it. It exists to find out how far live media can be pushed through a peer-to-peer context, and to report the answer honestly.",
      ],
      concepts: [
        { term: "Namespace", def: "A stream you own and invite viewers into." },
        { term: "Context", def: "The stream: its members, its frames and its chunks." },
        { term: "Frame", def: "A picture encoded by a deterministic, integer-only codec running inside the WASM app. No floating point, no SIMD, no threads — so every node computes a byte-identical result." },
        { term: "Chunk", def: "The other path: H.264 encoded by the browser’s WebCodecs and stored as fragments. Faster, but the browser is doing the encoding rather than the contract." },
        { term: "Tombstone", def: "How a deleted fragment is recorded. Fragment keys are monotone and never reused, so a delete can never be confused with a fragment that has not arrived yet." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Use a browser", body: "This app is web only. The desktop is not a supported target — it is not blocked there and does not crash; the integration around it is what is unsupported." },
        { title: "Connect a node", body: "Press Connect to node and choose your node." },
        { title: "Create a stream", body: "A namespace you own. You are its admin." },
        { title: "Watch the numbers", body: "Throughput and delivery are reported as you go. That measurement is the actual output of this app." },
      ],
    },
    {
      id: "sharing",
      heading: "What it is honest about",
      paragraphs: [
        "Measured, not promised. Presence-based delivery carries roughly 96% of frames with one author and materially less with two — the bandwidth arithmetic suggested a higher number and the measurement did not agree.",
        "The deterministic codec is deliberately primitive. It exists so that every peer computes an identical frame, which makes the capacity question answerable at all.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Members and their roles.",
        "Frames from the deterministic codec, with a sequence number and a checksum.",
        "Media chunks from the WebCodecs path, with cursors marking keyframes.",
        "Pruning counters, so old frames can be dropped without breaking the monotone sequence.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "Frames are dropping", def: "Expected, and the point. The app reports what got through rather than pretending everything did." },
        { term: "The camera does not start", def: "WebCodecs H.264 needs a browser build that ships the codec. A stock Chromium without it will not encode." },
        { term: "It behaves oddly in the desktop app", def: "Web only. Use a browser." },
      ],
    },
  ],
  previewSteps: [
    { title: "Two nodes", body: "An encoder and a decoder, with a real context between them rather than a media server." },
    { title: "Frames flow", body: "Either deterministic frames computed inside the WASM app, or browser-encoded H.264 chunks." },
    { title: "Throughput is measured", body: "The bar is the actual figure, not an illustration. Measuring it is what this app is for." },
    { title: "The ceiling is reported", body: "Where delivery falls off, the app says so. An honest experiment beats a confident demo." },
  ],
  loginPopup: LoginPopup,
};
