/**
 * Landing content for Mero Meet.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { CloudX, ExternalLink, Shield, Wifi } from '@calimero-network/mero-icons';

import Animation from './animation';
import LoginPopup from './loginPopup';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Meet",
  packageId: "com.calimero.mero-meet",
  tagline: "Decentralized, peer-to-peer video calling on Calimero. WebRTC media; signaling rides your nodes — no signaling server.",
  dir: "mero-meet",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "desktop",
  themeStorageKey: "mm-theme",
  trust: ["Media stays peer-to-peer", "No signalling server", "Rooms are namespaces"],
  explainer: [
    "Peer-to-peer video calling, split across two planes. A Calimero context is the room and carries the signalling; the audio and video go directly between participants over WebRTC and never touch a server at all.",
    "The signalling is the part other \"peer-to-peer\" calling apps still centralise — someone has to introduce the peers to each other, and that someone usually gets to see who called whom and when. Here the introduction rides your own nodes.",
  ],
  features: [
    {
      icon: Wifi,
      title: "Media stays peer-to-peer",
      body: "WebRTC between participants. Your camera and microphone never reach a server.",
    },
    {
      icon: Shield,
      title: "Signalling rides your nodes",
      body: "The room is a context you own, not a service you rent. Nobody logs the call graph.",
    },
    {
      icon: CloudX,
      title: "No signalling server",
      body: "The piece almost every other p2p calling app still centralises, removed.",
    },
    {
      icon: ExternalLink,
      title: "Invite by link",
      body: "The room is a namespace. Share an invitation, and membership is the access control.",
    },
  ],
  faq: [
    {
      q: "Why does this need the desktop app?",
      a: "Mero Meet uses the Calimero desktop app for its node, its sign-in, and the media bridge that connects WebRTC to the room. On the plain web there is no node to talk to, so this page is the front door rather than the app itself.",
    },
  ],
  animation: Animation,
  docs: [
    {
      id: "concepts",
      heading: "The words, and what they mean here",
      paragraphs: [
        "Mero Meet splits a call across two planes. A Calimero context is the room and carries the signalling; the audio and video go directly peer-to-peer over WebRTC. No signalling server is the part every other \"p2p\" calling app still centralises.",
      ],
      concepts: [
        { term: "Namespace", def: "A room you own and invite people into." },
        { term: "Context", def: "The room’s membership, lobby, chat and — crucially — the signalling messages." },
        { term: "Signal", def: "A WebRTC offer, answer or ICE candidate, posted into the context and read by the other participant. This is the job a signalling server normally does." },
        { term: "Media", def: "The audio and video. It never enters the context and never touches a server: once signalling has done its work, the streams are a direct connection between the two browsers." },
        { term: "Host", def: "A grantable role. The room name is owner-gated, so a rename from a non-owner is rejected at merge." },
      ],
    },
    {
      id: "start",
      heading: "Getting started",
      steps: [
        { title: "Install the desktop app", body: "Mero Meet needs the Calimero desktop app for its node, sign-in and media bridge. This web page is the front door, not the product." },
        { title: "Create a room", body: "A namespace you own. Name it; you are its host." },
        { title: "Invite people", body: "Share the link. Joining puts them in the lobby." },
        { title: "Start the call", body: "Signalling flows through the context, then the media connects directly between participants." },
      ],
    },
    {
      id: "sharing",
      heading: "Who can join",
      paragraphs: [
        "Only members of the room’s namespace. An invitation is a link scoped to that room; there is no dial-in number and no public URL that anyone can open.",
        "Host is a role you grant and revoke. Leaving a call is separate from leaving the room, so stepping out does not remove you from the membership.",
      ],
    },
    {
      id: "storage",
      heading: "What is stored, and where",
      bullets: [
        "Members, their presence, and the lobby.",
        "Signalling messages, which are what the room exists to carry.",
        "Chat messages posted during a call.",
        "No media, ever. Audio and video are not written to the context and are not recorded.",
      ],
    },
    {
      id: "offline",
      heading: "Offline, and what happens when you reconnect",
      paragraphs: [
        "Your node holds the whole state, so the app keeps working with no network — every change is written locally and queued.",
        "When your node reaches a peer again, the two exchange changes and merge them. Merging is CRDT-based, not last-write-wins-by-clock, so two people editing different things at the same time both keep their work. Where two people genuinely changed the same single value, the later write wins on that one value and nothing else is lost.",
      ],
    },
    {
      id: "trouble",
      heading: "When something looks wrong",
      concepts: [
        { term: "\"Connect to node\" is not offered on the web", def: "Deliberate. This app needs the desktop app’s node and media bridge, so offering a connection it cannot use would be a dead end." },
        { term: "Someone joined but has no video", def: "Signalling succeeded and the media connection did not. That is a WebRTC path problem between the two networks, not a Calimero one." },
        { term: "A rename reverted", def: "The room name is owner-gated and a non-owner’s rename is refused when it merges." },
      ],
    },
  ],
  previewSteps: [
    { title: "A room, in a context", body: "Membership and the lobby live in a Calimero context you own." },
    { title: "Participants join", body: "Each arrival is a member of the namespace — there is no public join link for strangers." },
    { title: "Signalling rides the context", body: "Offers, answers and ICE candidates are posted into the room. This is the piece normally rented from a server." },
    { title: "Media goes direct", body: "Audio and video connect browser to browser and are never written down anywhere." },
  ],
  loginPopup: LoginPopup,
};
