/**
 * Landing page contract for Mero Design.
 *
 * GENERATED by `pnpm landing:generate`. Do not edit — `pnpm landing:check`
 * fails CI on drift. The assertions live in scripts/landing/generate.mjs.
 */
import { test, expect } from '@playwright/test';

test.describe('Mero Design landing page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('hero names the app and its tagline', async ({ page }) => {
    await expect(page.getByRole('heading', { level: 1, name: "Mero Design" })).toBeVisible();
    await expect(page.locator('.cal-lp-lede')).toBeVisible();
  });

  test('shows the availability badge', async ({ page }) => {
    await expect(page.getByText("Web + Desktop", { exact: true })).toBeVisible();
  });

  test('every section is present and NOT blank', async ({ page }) => {
    // Deliberately asserted without scrolling. A reveal that gates on an
    // IntersectionObserver renders these blank in a headless capture, which is
    // the bug this fleet hit twice.
    for (const id of ['about', 'features', 'how', 'faq']) {
      await expect(page.locator(`#${id}`)).toBeVisible();
    }
    await expect(page.locator('.cal-lp-feature')).toHaveCount(6);
    await expect(page.locator('.cal-lp-step')).toHaveCount(4);
  });

  test('the theme toggle flips the palette both ways', async ({ page }) => {
    const root = page.locator('.cal-lp-root');
    const toggle = page.getByRole('button', { name: /Switch to (light|dark) theme/ });
    await toggle.click();
    const first = await root.getAttribute('data-cal-lp-theme');
    expect(first === 'dark' || first === 'light').toBe(true);
    await toggle.click();
    const second = await root.getAttribute('data-cal-lp-theme');
    expect(second).not.toBe(first);
  });

  test('a FAQ answer opens', async ({ page }) => {
    const first = page.locator('.cal-lp-faqq').first();
    await expect(first).toHaveAttribute('aria-expanded', 'false');
    await first.click();
    await expect(first).toHaveAttribute('aria-expanded', 'true');
    await expect(page.locator('.cal-lp-faqa').first()).toBeVisible();
  });

  test('does not scroll sideways on a phone', async ({ page }) => {
    await page.setViewportSize({ width: 400, height: 780 });
    const overflow = await page.evaluate(
      () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
    );
    expect(overflow).toBeLessThanOrEqual(1);
  });

  test('offers the desktop download', async ({ page }) => {
    await expect(
      page.locator('a[href="https://calimero.network/download"]').first(),
    ).toBeVisible();
  });

  test('offers a way to connect', async ({ page }) => {
    const link = page.getByRole('link', { name: 'Connect to node' }).first();
    const button = page.getByRole('button', { name: 'Connect to node' }).first();
    expect((await link.count()) + (await button.count())).toBeGreaterThan(0);
  });
});
