#!/usr/bin/env node
/**
 * Render the shared landing template into every app.
 *
 *   node scripts/landing/generate.mjs           # write
 *   node scripts/landing/generate.mjs --check   # verify, write nothing (CI)
 *
 * WHY A GENERATOR AND NOT A SHARED PACKAGE
 * Each app owning a real local file means it typechecks, tests and builds on its
 * own with no workspace indirection — which is what was asked for. The cost of
 * copying is that fourteen copies drift, and in a year no two are the same
 * again, which is the exact problem "one unified landing page" exists to solve.
 * So the copies are generated: the template is the single source, `--check`
 * fails CI the moment a copy diverges, and the only hand-owned files are each
 * app's `landing.config.ts` and its animation component.
 *
 * WHY THE COPY IS VERBATIM
 * There is no templating language here. `LandingPage.tsx`, `landing.css` and
 * `landingTypes.ts` are real TypeScript/CSS that import `./landing.config`, so
 * "rendering" is a byte-for-byte copy plus one generated config per app. That
 * makes the drift check a file comparison rather than a re-render, and it means
 * the template can be typechecked directly instead of only after substitution.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { APPS } from './apps.config.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const TEMPLATE = join(HERE, 'template');

/** Copied verbatim into every app. Anything here is NOT app-specific. */
const VERBATIM = ['LandingPage.tsx', 'landing.css', 'landingTypes.ts'];

const CHECK = process.argv.includes('--check');

/**
 * The app's own metadata table — the same one the registry publishes from, so
 * the landing page's title and description cannot drift from the listing.
 * Deliberately read here rather than duplicated into apps.config.mjs.
 */
function readCalimeroMeta(app) {
  const candidates = [];
  const logic = join(ROOT, 'apps', app, 'logic');
  const walk = (dir, depth = 0) => {
    if (depth > 3 || !existsSync(dir)) return;
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.name === 'target' || e.name === 'node_modules') continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p, depth + 1);
      else if (e.name === 'Cargo.toml') candidates.push(p);
    }
  };
  walk(logic);

  for (const f of candidates) {
    const src = readFileSync(f, 'utf8');
    const block = src.match(/^\[package\.metadata\.calimero\]\s*$([\s\S]*?)(?=^\[|\Z)/m);
    if (!block) continue;
    const body = block[1];
    const get = (k) => body.match(new RegExp(`^\\s*${k}\\s*=\\s*"([^"]*)"`, 'm'))?.[1];
    const pkg = get('package');
    if (!pkg) continue;
    const name = get('name');
    const description = get('description');
    if (!name || !description) {
      throw new Error(`${app}: [package.metadata.calimero] is missing name or description (${f})`);
    }
    return { packageId: pkg, name, tagline: description };
  }
  throw new Error(`${app}: no [package.metadata.calimero] table with a package id found`);
}

/** The named mero-icons imports this app's features need, deduped and sorted. */
function iconImports(entry) {
  const names = [...new Set(entry.features.map((f) => f.icon))].sort();
  for (const n of names) {
    if (!/^[A-Z][A-Za-z0-9]*$/.test(n)) throw new Error(`bad icon name: ${n}`);
  }
  return names;
}

const q = (s) => JSON.stringify(s);

/**
 * One generated e2e spec per app, asserting the UNIFIED contract.
 *
 * Seven apps had a hand-written `landing.spec.ts` asserting their bespoke page —
 * different selectors, different copy, different counts, and between them no
 * agreement on what a landing page must do. Those are replaced by this, for the
 * same reason the page itself is generated: fourteen specs that drift are
 * fourteen specs that stop meaning anything.
 *
 * Needs no node and no auth. The landing page is the unauthenticated front
 * door, so a plain vite server is the whole harness.
 */
function renderSpec(app, entry, meta) {
  meta = { ...meta, name: entry.displayName ?? meta.name };
  const desktopOnly = entry.availability === 'desktop';
  const badge = desktopOnly ? 'Desktop only' : entry.availability === 'web' ? 'Web only' : 'Web + Desktop';
  return `/**
 * Landing page contract for ${meta.name}.
 *
 * GENERATED by \`pnpm landing:generate\`. Do not edit — \`pnpm landing:check\`
 * fails CI on drift. The assertions live in scripts/landing/generate.mjs.
 */
import { test, expect } from '@playwright/test';

test.describe('${meta.name} landing page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('hero names the app and its tagline', async ({ page }) => {
    await expect(page.getByRole('heading', { level: 1, name: ${q(meta.name)} })).toBeVisible();
    await expect(page.locator('.cal-lp-lede')).toBeVisible();
  });

  test('shows the availability badge', async ({ page }) => {
    // Scoped to the badge row on purpose: the same words legitimately appear
    // again in the trust strip, and an unscoped getByText is a strict-mode
    // violation the moment an app says both.
    await expect(
      page.locator('.cal-lp-badge').filter({ hasText: ${q(badge)} }),
    ).toHaveCount(1);
  });

  test('every section is present and NOT blank', async ({ page }) => {
    // Deliberately asserted without scrolling. A reveal that gates on an
    // IntersectionObserver renders these blank in a headless capture, which is
    // the bug this fleet hit twice.
    for (const id of ['about', 'features', 'how', 'faq']) {
      await expect(page.locator(\`#\${id}\`)).toBeVisible();
    }
    await expect(page.locator('.cal-lp-feature')).toHaveCount(${entry.features.length});
    await expect(page.locator('.cal-lp-step')).toHaveCount(4);
  });

  test('defaults to light, even when the OS asks for dark', async ({ page }) => {
    // The page is deliberately NOT prefers-color-scheme aware: a landing page
    // is the first thing a stranger sees, and the same page in a screenshot, a
    // review and a share card. Dark is reachable only by clicking the toggle.
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.reload();
    const root = page.locator('.cal-lp-root');
    await expect(root).toHaveAttribute('data-cal-lp-theme', 'light');
    // The attribute states the intent; this is what actually got painted. A
    // stray prefers-color-scheme rule anywhere in landing.css would pass the
    // line above and fail this one.
    await expect(root).toHaveCSS('background-color', 'rgb(252, 252, 252)');

    // ⚠️ And again on a REPEAT visit, which is a different code path and the
    // one that was actually broken. mero-calendar, mero-meet, mero-sheets and
    // mero-issue-tracker each seed their own ThemeProvider from
    // prefers-color-scheme and then WRITE that to localStorage in a mount
    // effect — so a one-shot check sees light (the effect has not run yet)
    // while every visit after it is dark.
    await page.reload();
    await expect(root).toHaveAttribute('data-cal-lp-theme', 'light');
    await expect(root).toHaveCSS('background-color', 'rgb(252, 252, 252)');
  });

  test('the theme toggle flips the palette both ways', async ({ page }) => {
    const root = page.locator('.cal-lp-root');
    const toggle = page.getByRole('button', { name: /Switch to (light|dark) theme/ });
    await toggle.click();
    const first = await root.getAttribute('data-cal-lp-theme');
    expect(first === 'dark' || first === 'light').toBe(true);
    await toggle.click();
    const second = await root.getAttribute('data-cal-lp-theme');
    expect(second).not.toBe(first);
  });

  test('a FAQ answer opens', async ({ page }) => {
    const first = page.locator('.cal-lp-faqq').first();
    await expect(first).toHaveAttribute('aria-expanded', 'false');
    await first.click();
    await expect(first).toHaveAttribute('aria-expanded', 'true');
    await expect(page.locator('.cal-lp-faqa').first()).toBeVisible();
  });

  // 320px is the narrowest phone still in use and 390 is the common one. Both,
  // because the header and the hero art break at different widths.
  for (const width of [390, 320]) {
    test(\`does not scroll sideways on a \${width}px phone\`, async ({ page }) => {
      await page.setViewportSize({ width, height: 780 });
      // Measured on the landing root as well as the document.
      //
      // ⚠️ The document alone is VACUOUS for the two canvas games: their
      // mount.tsx renders this page into a fixed, inset-0, overflow-y-auto
      // host, so nothing it contains can ever move
      // documentElement.scrollWidth and the assertion passes without looking.
      const overflow = await page.evaluate(() => {
        const root = document.querySelector('.cal-lp-root');
        const doc = document.documentElement;
        return Math.max(
          doc.scrollWidth - doc.clientWidth,
          root ? root.scrollWidth - root.clientWidth : 0,
          root?.parentElement
            ? root.parentElement.scrollWidth - root.parentElement.clientWidth
            : 0,
        );
      });
      expect(overflow).toBeLessThanOrEqual(1);
    });
  }

  test('the header stays one line on a phone', async ({ page }) => {
    // \`Mero Issue Tracker\` wrapped under its own icon and pushed the sticky
    // header from 60px to 120px, eating a fifth of the screen on every scroll.
    await page.setViewportSize({ width: 360, height: 780 });
    const header = page.locator('.cal-lp-header');
    await expect(header).toBeVisible();
    const box = await header.boundingBox();
    expect(box?.height ?? 0).toBeLessThanOrEqual(72);
  });

  test('the hero art is drawn to fit its frame on a phone', async ({ page }) => {
    // The animations position their parts in literal pixels against a 495px
    // stage, so an unscaled box writes its rows over each other inside a 328px
    // phone frame. useStageScale() is what stops that, and it is invisible in
    // a screenshot review until you measure it.
    await page.setViewportSize({ width: 360, height: 780 });
    const body = page.locator('.cal-lp-stagebody');
    await expect(body).toBeVisible();
    const art = page.locator('.cal-lp-a').first();
    await expect(art).toBeAttached();
    const [bodyBox, artBox] = await Promise.all([body.boundingBox(), art.boundingBox()]);
    // Rendered width, after the scale — within a pixel of the frame it sits in.
    expect(Math.abs((artBox?.width ?? 0) - (bodyBox?.width ?? 0))).toBeLessThanOrEqual(1.5);
  });

  test('offers the desktop download', async ({ page }) => {
    await expect(
      page.locator('a[href="https://calimero.network/download"]').first(),
    ).toBeVisible();
  });
${desktopOnly ? `
  test('a desktop-only app does not offer a node it cannot reach', async ({ page }) => {
    // Wait for the page to actually exist first — \`toHaveCount(0)\` passes
    // instantly against a blank document, which would make this vacuous.
    await expect(page.locator('.cal-lp-hero')).toBeVisible();
    await expect(page.locator('a, button').filter({ hasText: /^Connect to node$/ })).toHaveCount(0);
  });
` : `
  test('offers a way to connect', async ({ page }) => {
    // \`count()\` takes one synchronous reading and never retries, so asserting
    // on it races React's first paint. The CTA is a link for most apps and a
    // button for the ones whose sign-in is in-page, hence the union selector,
    // which \`toBeVisible\` then waits on properly.
    await expect(
      page
        .locator('a, button')
        .filter({ hasText: /^Connect to node$/ })
        .first(),
    ).toBeVisible();
  });
`}});
`;
}

function renderConfig(app, entry, meta) {
  // Presentation-only override. The registry metadata stays exactly as
  // published — this changes the heading on the web page and nothing else.
  meta = { ...meta, name: entry.displayName ?? meta.name };
  const icons = iconImports(entry);
  const lines = [];

  lines.push('/**');
  lines.push(` * Landing content for ${meta.name}.`);
  lines.push(' *');
  lines.push(' * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs');
  lines.push(' * plus this app\'s [package.metadata.calimero] table. Do not edit by hand —');
  lines.push(' * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.');
  lines.push(' *');
  lines.push(' * `name`, `packageId` and `tagline` come from the Cargo metadata the registry');
  lines.push(' * publishes from, so this page and the registry listing cannot diverge.');
  lines.push(' */');
  lines.push(`import { ${icons.join(', ')} } from '@calimero-network/mero-icons';`);
  lines.push('');
  // An app's animation is hand-owned: the ONE piece that should differ per app,
  // and the one this generator must never overwrite. Wired in only if present.
  const hasAnimation = existsSync(
    join(ROOT, 'apps', app, 'app', 'src', 'pages', 'landing', 'animation.tsx'),
  );
  if (hasAnimation) lines.push("import Animation from './animation';");
  lines.push("import type { LandingConfig } from './landingTypes';");
  lines.push('');
  lines.push('export const CONFIG: LandingConfig = {');
  lines.push(`  name: ${q(meta.name)},`);
  lines.push(`  packageId: ${q(meta.packageId)},`);
  lines.push(`  tagline: ${q(meta.tagline)},`);
  lines.push(`  dir: ${q(app)},`);
  lines.push(`  markSrc: ${q(entry.markSrc ?? '/favicon.svg')},`);
  lines.push(`  iconSrc: '/icon-512.png',`);
  lines.push(`  availability: ${q(entry.availability)},`);
  if (entry.themeStorageKey) lines.push(`  themeStorageKey: ${q(entry.themeStorageKey)},`);
  if (entry.experimental) lines.push('  experimental: true,');
  if (entry.playableOffline) lines.push('  playableOffline: true,');
  lines.push(`  trust: [${entry.trust.map(q).join(', ')}],`);
  lines.push('  explainer: [');
  for (const p of entry.explainer) lines.push(`    ${q(p)},`);
  lines.push('  ],');
  lines.push('  features: [');
  for (const f of entry.features) {
    lines.push('    {');
    lines.push(`      icon: ${f.icon},`);
    lines.push(`      title: ${q(f.title)},`);
    lines.push(`      body: ${q(f.body)},`);
    lines.push('    },');
  }
  lines.push('  ],');
  if (entry.faq?.length) {
    lines.push('  faq: [');
    for (const f of entry.faq) {
      lines.push('    {');
      lines.push(`      q: ${q(f.q)},`);
      lines.push(`      a: ${q(f.a)},`);
      lines.push('    },');
    }
    lines.push('  ],');
  }
  if (hasAnimation) lines.push('  animation: Animation,');
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

const templateFiles = Object.fromEntries(
  VERBATIM.map((f) => [f, readFileSync(join(TEMPLATE, f), 'utf8')]),
);

let wrote = 0;
const drift = [];

for (const [app, entry] of Object.entries(APPS)) {
  const outDir = join(ROOT, 'apps', app, 'app', 'src', 'pages', 'landing');
  const meta = readCalimeroMeta(app);
  const files = { ...templateFiles, 'landing.config.ts': renderConfig(app, entry, meta) };

  // ALWAYS `marketing-landing.spec.ts`, never `landing.spec.ts`. Half the fleet
  // already owned a hand-written `e2e/landing.spec.ts` — covering route guards
  // and redirects, which this page's spec says nothing about — and generating
  // over that name silently deleted them.
  const SPEC_NAME = 'marketing-landing.spec.ts';
  const specDest = join(ROOT, 'apps', app, 'app', entry.e2eDir, SPEC_NAME);
  const targets = Object.entries(files).map(([n, c]) => [join(outDir, n), c, n]);
  targets.push([specDest, renderSpec(app, entry, meta), `${entry.e2eDir}/${SPEC_NAME}`]);

  for (const [dest, content, name] of targets) {
    const current = existsSync(dest) ? readFileSync(dest, 'utf8') : null;
    if (current === content) continue;
    if (CHECK) {
      drift.push(`  apps/${app}/app/… ${name}` + (current === null ? '  (missing)' : ''));
      continue;
    }
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, content);
    wrote += 1;
  }
}

if (CHECK) {
  if (drift.length) {
    console.error('landing: generated files are out of date or missing:\n' + drift.join('\n'));
    console.error('\nRun `pnpm landing:generate` and commit the result.');
    process.exit(1);
  }
  console.log(`landing: all ${Object.keys(APPS).length} apps match the template.`);
} else {
  console.log(
    wrote === 0
      ? `landing: already up to date (${Object.keys(APPS).length} apps).`
      : `landing: wrote ${wrote} file(s) across ${Object.keys(APPS).length} apps.`,
  );
}
