/**
 * Landing page contract for Mero Stream.
 *
 * GENERATED by `pnpm landing:generate`. Do not edit — `pnpm landing:check`
 * fails CI on drift. The assertions live in scripts/landing/generate.mjs.
 */
import { test, expect } from '@playwright/test';

test.describe('Mero Stream landing page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('hero names the app and its tagline', async ({ page }) => {
    await expect(page.getByRole('heading', { level: 1, name: "Mero Stream" })).toBeVisible();
    await expect(page.locator('.cal-lp-lede')).toBeVisible();
  });

  test('shows the availability badge', async ({ page }) => {
    // Scoped to the badge row on purpose: the same words legitimately appear
    // again in the trust strip, and an unscoped getByText is a strict-mode
    // violation the moment an app says both.
    await expect(
      page.locator('.cal-lp-badge').filter({ hasText: "Web only" }),
    ).toHaveCount(1);
  });

  test('every section is present and NOT blank', async ({ page }) => {
    // Deliberately asserted without scrolling. A reveal that gates on an
    // IntersectionObserver renders these blank in a headless capture, which is
    // the bug this fleet hit twice.
    for (const id of ['about', 'features', 'how', 'faq']) {
      await expect(page.locator(`#${id}`)).toBeVisible();
    }
    await expect(page.locator('.cal-lp-feature')).toHaveCount(4);
    await expect(page.locator('.cal-lp-step')).toHaveCount(4);
  });

  test('the theme toggle flips the palette both ways', async ({ page }) => {
    const root = page.locator('.cal-lp-root');
    const toggle = page.getByRole('button', { name: /Switch to (light|dark) theme/ });
    await toggle.click();
    const first = await root.getAttribute('data-cal-lp-theme');
    expect(first === 'dark' || first === 'light').toBe(true);
    await toggle.click();
    const second = await root.getAttribute('data-cal-lp-theme');
    expect(second).not.toBe(first);
  });

  test('a FAQ answer opens', async ({ page }) => {
    const first = page.locator('.cal-lp-faqq').first();
    await expect(first).toHaveAttribute('aria-expanded', 'false');
    await first.click();
    await expect(first).toHaveAttribute('aria-expanded', 'true');
    await expect(page.locator('.cal-lp-faqa').first()).toBeVisible();
  });

  // 320px is the narrowest phone still in use and 390 is the common one. Both,
  // because the header and the hero art break at different widths.
  for (const width of [390, 320]) {
    test(`does not scroll sideways on a ${width}px phone`, async ({ page }) => {
      await page.setViewportSize({ width, height: 780 });
      // Measured on the landing root as well as the document.
      //
      // ⚠️ The document alone is VACUOUS for the two canvas games: their
      // mount.tsx renders this page into a fixed, inset-0, overflow-y-auto
      // host, so nothing it contains can ever move
      // documentElement.scrollWidth and the assertion passes without looking.
      const overflow = await page.evaluate(() => {
        const root = document.querySelector('.cal-lp-root');
        const doc = document.documentElement;
        return Math.max(
          doc.scrollWidth - doc.clientWidth,
          root ? root.scrollWidth - root.clientWidth : 0,
          root?.parentElement
            ? root.parentElement.scrollWidth - root.parentElement.clientWidth
            : 0,
        );
      });
      expect(overflow).toBeLessThanOrEqual(1);
    });
  }

  test('the header stays one line on a phone', async ({ page }) => {
    // `Mero Issue Tracker` wrapped under its own icon and pushed the sticky
    // header from 60px to 120px, eating a fifth of the screen on every scroll.
    await page.setViewportSize({ width: 360, height: 780 });
    const header = page.locator('.cal-lp-header');
    await expect(header).toBeVisible();
    const box = await header.boundingBox();
    expect(box?.height ?? 0).toBeLessThanOrEqual(72);
  });

  test('the hero art is drawn to fit its frame on a phone', async ({ page }) => {
    // The animations position their parts in literal pixels against a 495px
    // stage, so an unscaled box writes its rows over each other inside a 328px
    // phone frame. useStageScale() is what stops that, and it is invisible in
    // a screenshot review until you measure it.
    await page.setViewportSize({ width: 360, height: 780 });
    const body = page.locator('.cal-lp-stagebody');
    await expect(body).toBeVisible();
    const art = page.locator('.cal-lp-a').first();
    await expect(art).toBeAttached();
    const [bodyBox, artBox] = await Promise.all([body.boundingBox(), art.boundingBox()]);
    // Rendered width, after the scale — within a pixel of the frame it sits in.
    expect(Math.abs((artBox?.width ?? 0) - (bodyBox?.width ?? 0))).toBeLessThanOrEqual(1.5);
  });

  test('offers the desktop download', async ({ page }) => {
    await expect(
      page.locator('a[href="https://calimero.network/download"]').first(),
    ).toBeVisible();
  });

  test('offers a way to connect', async ({ page }) => {
    // `count()` takes one synchronous reading and never retries, so asserting
    // on it races React's first paint. The CTA is a link for most apps and a
    // button for the ones whose sign-in is in-page, hence the union selector,
    // which `toBeVisible` then waits on properly.
    await expect(
      page
        .locator('a, button')
        .filter({ hasText: /^Connect to node$/ })
        .first(),
    ).toBeVisible();
  });
});
