/**
 * Landing content for Mero Sign.
 *
 * GENERATED by `pnpm landing:generate` from scripts/landing/apps.config.mjs
 * plus this app's [package.metadata.calimero] table. Do not edit by hand —
 * `pnpm landing:check` fails CI on drift. Change the copy in apps.config.mjs.
 *
 * `name`, `packageId` and `tagline` come from the Cargo metadata the registry
 * publishes from, so this page and the registry listing cannot diverge.
 */
import { ExternalLink, FileCheck, GlobeCheck, LockBox, ShieldCheck } from '@calimero-network/mero-icons';

import Animation from './animation';
import type { LandingConfig } from './landingTypes';

export const CONFIG: LandingConfig = {
  name: "Mero Sign",
  packageId: "com.calimero.mero-sign",
  tagline: "Document signing on Calimero - upload a PDF, collect signatures from namespace members, and verify them peer-to-peer.",
  dir: "mero-sign",
  markSrc: "/favicon.svg",
  iconSrc: '/icon-512.png',
  availability: "web+desktop",
  trust: ["No signing service", "Roles per signatory", "Verify peer-to-peer"],
  explainer: [
    "Upload a PDF, collect signatures from the people you invite, and verify them — with no e-signature company in the middle holding your contracts and charging per envelope.",
    "An agreement is a shared context you administer. Signatories join by invitation and sign in the roles you assigned them, and your own signature library stays in a private context that only you can read.",
  ],
  features: [
    {
      icon: FileCheck,
      title: "Agreements as contexts",
      body: "Create one and you administer it. Membership and roles are yours to set.",
    },
    {
      icon: ShieldCheck,
      title: "Role-based signing",
      body: "Each signatory signs in the role you assigned, so the document knows who still owes a signature.",
    },
    {
      icon: LockBox,
      title: "A private signature library",
      body: "Your signatures live in a local context only you can read, not in a vendor’s account.",
    },
    {
      icon: ExternalLink,
      title: "Invitations tied to identities",
      body: "Scoped invite payloads with permissions, bound to Calimero identities rather than email addresses.",
    },
    {
      icon: GlobeCheck,
      title: "Verify peer-to-peer",
      body: "Check a signature without asking a service whether it is genuine.",
    },
  ],
  animation: Animation,
};
