[package]
name    = "battleships-types"
version = "0.1.0"
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
bs58      = { workspace = true }
borsh     = { workspace = true, features = ["derive"] }
serde     = { version = "1.0", features = ["derive"] }
